//! Coordinator with callbacks for intermediate content
//!
//! Provides:
//! - Pre-tool content callbacks (content before tool calls)
//! - Thinking content callbacks
//! - Full control over tool execution flow
//! - Inter-tool context overflow detection

/// Error string returned when the user cancels tool execution (Ctrl+C).
/// Checked by the caller (`handle_user_message_stream`) to suppress error display.
pub const CANCELLED_BY_USER: &str = "CANCELLED_BY_USER";

use std::{collections::HashMap, future::Future, pin::Pin};

use serde::Deserialize;
use serde_json::Value;

use crate::chat::llm_event::LlmEvent;
use crate::context_overflow::{
    calculate_available_budget, calculate_thresholds, is_emergency_context,
    needs_inter_tool_compaction,
};
use crate::provider::LlmProvider;
use crate::provider::OpenAICompatibleProvider;
use crate::provider::types::{
    LlmMessage, LlmResponse, LlmRole, LlmStreamEvent, LlmToolCall, LlmUsage, ProviderError,
    ProviderOptions, ToolInfo,
};
use crate::tokens::{ContextUsage, MESSAGE_OVERHEAD, estimate_tokens};
use crate::utils::truncate_to_budget;

/// Result type for tool execution
pub type ToolResult = std::result::Result<String, Box<dyn std::error::Error + Send + Sync>>;

/// Trait to hold and call tools - our own implementation since ollama-rs's ToolHolder is private.
/// Bound is `Send` (not `Send + Sync`) because tool futures await
/// `LlmProvider::embed`/`chat` which are Send only.
pub trait ToolHolder: Send {
    fn call(&mut self, parameters: Value) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send>>;
}

impl<T: crate::tools::Tool> ToolHolder for T {
    fn call(&mut self, parameters: Value) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send>> {
        Box::pin(async move {
            // Handle different JSON formats that models might return
            let param_value =
                match serde_json::from_value::<ToolCallFunctionParser>(parameters.clone()) {
                    Ok(func) => func.arguments,
                    Err(_) => parameters,
                };

            let params: T::Params = serde_json::from_value(param_value)?;
            T::call(self, params).await
        })
    }
}

/// Helper struct for parsing tool call function JSON
#[derive(Deserialize)]
struct ToolCallFunctionParser {
    #[expect(dead_code)]
    name: String,
    arguments: Value,
}

/// Pre-tool content accumulated during processing
///
/// Contains text generated by the assistant before tool calls,
/// which should be saved separately from the final response.
#[derive(Debug, Clone, Default)]
pub struct PreToolContent {
    /// Content generated before tool calls
    pub content: String,
    /// Thinking content (if any)
    pub thinking: Option<String>,
}

/// Continuation tag parsed from LLM response
///
/// When the LLM detects context is nearly full and needs to pause,
/// it emits this tag with checkpoint information for resumption.
#[derive(Debug, Clone)]
pub struct ContinuationTag {
    /// Where reasoning was paused
    pub paused_at: String,
    /// What the LLM was about to do next
    pub next_step: String,
}

/// Parse continuation tag from LLM response
///
/// Extracts the <continuation_needed> tag content and returns
/// both the cleaned response (without the tag) and the parsed tag.
///
/// Returns (cleaned_content, Some(tag)) if tag found and parsed,
/// or (original_content, None) if no tag or invalid.
pub fn parse_continuation_tag(content: &str) -> (String, Option<ContinuationTag>) {
    // Find the tag
    let start_tag = "<continuation_needed>";
    let end_tag = "</continuation_needed>";

    let start_pos = match content.find(start_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Check if tag is inside a code block (should NOT be parsed)
    let before_tag = &content[..start_pos];
    let code_block_count = before_tag.matches("```").count();
    if code_block_count % 2 == 1 {
        // Inside a code block, don't parse
        return (content.to_string(), None);
    }

    let end_pos = match content.find(end_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Extract tag content
    let tag_content = &content[start_pos + start_tag.len()..end_pos];

    // Parse fields
    let mut paused_at = String::new();
    let mut next_step = String::new();

    for line in tag_content.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("Reasoning paused:") {
            paused_at = value.trim().to_string();
        } else if let Some(value) = line.strip_prefix("Next step:") {
            next_step = value.trim().to_string();
        }
    }

    // Create cleaned content by removing the tag
    let cleaned = format!(
        "{}{}",
        &content[..start_pos],
        &content[end_pos + end_tag.len()..]
    );

    // Normalize whitespace in cleaned content
    let cleaned = cleaned.trim().to_string();

    // Require at least one field to be filled
    if paused_at.is_empty() && next_step.is_empty() {
        return (content.to_string(), None);
    }

    (
        cleaned,
        Some(ContinuationTag {
            paused_at,
            next_step,
        }),
    )
}

/// Event emitted during chat processing
#[derive(Debug, Clone)]
pub enum ChatEvent {
    /// Content generated before tool calls (often thinking/intro text).
    PreToolContent {
        content: String,
        thinking: Option<String>,
    },
    /// Context is near limit after tool execution (inter-tool threshold)
    /// Indicates compaction may be needed before next tool
    ContextNearLimit {
        tool_name: String,
        tokens_used: usize,
        context_window: usize,
    },
    /// Context was truncated during tool execution (emergency threshold)
    /// Indicates last tool result was truncated to fit
    ContextTruncated {
        tool_name: String,
        original_tokens: usize,
        new_tokens: usize,
        context_window: usize,
    },
    /// Context needs compaction during tool execution (compaction threshold)
    /// Signals that tool execution should pause for compaction
    ContextNeedsCompaction {
        tokens_used: usize,
        context_window: usize,
        tools_executed: Vec<String>,
    },
    /// Tool execution lifecycle events.
    ///
    /// Emitted when a tool starts and finishes execution. Full
    /// partial-output streaming is deferred to a follow-up PR.
    ToolExecutionStarted {
        /// Tool-call id this execution belongs to.
        tool_call_id: String,
        /// Tool name.
        name: String,
        /// Final parsed arguments.
        args: serde_json::Value,
    },
    ToolExecutionFinished {
        /// Tool-call id this execution belongs to.
        tool_call_id: String,
        /// Tool result string (or error message).
        result: String,
        /// Whether the tool returned an error.
        is_error: bool,
    },
}

/// Result of checking context overflow after tool execution
struct ContextCheckResult {
    /// The result to use (possibly truncated)
    result: String,
    /// Whether context is near limit (inter-tool threshold)
    is_near_limit: bool,
    /// Whether result was truncated (emergency threshold)
    was_truncated: bool,
    /// Tokens used (for events)
    tokens_used: usize,
    /// Whether compaction is needed before continuing
    needs_compaction: bool,
}

/// A coordinator for managing chat interactions with event callbacks.
pub struct Coordinator {
    model: String,
    provider: OpenAICompatibleProvider,
    options: ProviderOptions,
    history: Vec<LlmMessage>,
    tool_infos: Vec<ToolInfo>,
    tools: HashMap<String, Box<dyn ToolHolder>>,
    think: Option<bool>,
    /// Callback for events
    event_callback: Option<Box<dyn Fn(ChatEvent) + Send + Sync>>,
    /// Streaming token callback (stored for multi-round ReAct loops).
    token_callback: Option<Box<dyn Fn(String) + Send + Sync>>,
    /// Streaming thinking callback (stored for multi-round ReAct loops).
    thinking_callback: Option<Box<dyn Fn(String) + Send + Sync>>,
    /// Tool-call detected callback (stored for multi-round ReAct loops).
    tool_call_callback: Option<Box<dyn Fn() + Send + Sync>>,
    /// Tool-call preview callback (stored for multi-round ReAct loops).
    #[allow(clippy::type_complexity)] // signature mirrors `on_tool_call_preview` callback
    tool_preview_callback: Option<Box<dyn Fn(String, String, serde_json::Value) + Send + Sync>>,
    /// Provider retry/event callback (stored for multi-round ReAct loops).
    provider_event_callback: Option<Box<dyn Fn(LlmEvent) + Send + Sync>>,
    /// Context window size for overflow detection during tool execution
    context_window: Option<usize>,
    /// System prompt for token estimation
    system_prompt: Option<String>,
    /// Real token count from the provider's prompt_tokens (if available)
    real_history_tokens: Option<usize>,
    /// Number of messages in history at the start of this request.
    initial_message_count: usize,
    /// Accumulated pre-tool content (text generated before tool calls)
    pre_tool_content: String,
    pre_tool_thinking: Option<String>,
    /// Ephemeral messages (not persisted to history)
    ephemeral_messages: Vec<LlmMessage>,
    /// Cancellation token for aborting tool execution mid-loop.
    cancel_token: Option<tokio_util::sync::CancellationToken>,
    /// Monotonic counter for generating unique tool_call_ids.
    tool_call_counter: u64,
    /// Counter for retries inside the ReAct loop (process_next_stream).
    react_retry_count: u32,
    /// Stream ids emitted by the provider, kept in the same order as
    /// `tool_calls` so the ReAct execution loop can reuse them.
    stream_tool_call_ids: Vec<String>,
}

/// Mutable state accumulated during a single streaming turn.
/// Extracted from `stream_turn` to keep each event handler small and testable.
struct StreamTurnState {
    full_content: String,
    full_thinking: Option<String>,
    prompt_eval_count: Option<u32>,
    eval_count: Option<u32>,
    tool_calls: Vec<LlmToolCall>,
    tool_call_previews: std::collections::HashMap<u32, (String, String, serde_json::Value)>,
    tool_call_started_emitted: bool,
}

impl StreamTurnState {
    fn new() -> Self {
        Self {
            full_content: String::new(),
            full_thinking: None,
            prompt_eval_count: None,
            eval_count: None,
            tool_calls: Vec::new(),
            tool_call_previews: std::collections::HashMap::new(),
            tool_call_started_emitted: false,
        }
    }

    fn handle_text_delta(&mut self, delta: String, coordinator: &Coordinator) {
        if let Some(ref cb) = coordinator.token_callback {
            cb(delta.clone());
        }
        self.full_content.push_str(&delta);
    }

    fn handle_thinking_delta(&mut self, delta: String, coordinator: &Coordinator) {
        if let Some(ref cb) = coordinator.thinking_callback {
            cb(delta.clone());
        }
        self.full_thinking
            .get_or_insert_with(String::new)
            .push_str(&delta);
    }

    fn handle_tool_call_start(
        &mut self,
        index: u32,
        id: Option<String>,
        name: Option<String>,
        coordinator: &Coordinator,
    ) {
        // Emit `ToolCallStarted` once per turn so the event
        // loop transitions to `ToolCall` state immediately.
        if !self.tool_call_started_emitted {
            self.tool_call_started_emitted = true;
            if let Some(ref cb) = coordinator.tool_call_callback {
                cb();
            }
        }
        let id = id.unwrap_or_default();
        let name = name.unwrap_or_default();
        self.tool_call_previews.insert(
            index,
            (
                id.clone(),
                name.clone(),
                serde_json::Value::Object(serde_json::Map::new()),
            ),
        );
        if let Some(ref cb) = coordinator.tool_preview_callback {
            cb(id, name, serde_json::Value::Object(serde_json::Map::new()));
        }
    }

    fn handle_tool_call_delta(
        &mut self,
        index: u32,
        id: Option<String>,
        name_delta: Option<String>,
        argument_delta: String,
        coordinator: &Coordinator,
    ) {
        if let Some((existing_id, existing_name, existing_args)) =
            self.tool_call_previews.get_mut(&index)
        {
            if let Some(id) = id {
                *existing_id = id;
            }
            if let Some(name) = name_delta {
                *existing_name = name;
            }
            // Accumulate argument_delta from the start:
            // the initial args from ToolCallStart are an
            // empty object, while the first delta is partial
            // JSON that must be concatenated before parsing.
            let raw = match existing_args {
                serde_json::Value::String(s) => {
                    let mut s = s.clone();
                    s.push_str(&argument_delta);
                    s
                }
                serde_json::Value::Object(o) if o.is_empty() => argument_delta.clone(),
                _ => argument_delta.clone(),
            };
            let parsed = serde_json::from_str(&raw).unwrap_or_else(|_| {
                if raw.is_empty() {
                    serde_json::Value::Object(serde_json::Map::new())
                } else {
                    serde_json::Value::String(raw.clone())
                }
            });
            *existing_args = parsed.clone();
            if let Some(ref cb) = coordinator.tool_preview_callback {
                cb(existing_id.clone(), existing_name.clone(), parsed);
            }
        }
    }

    fn handle_tool_call_end(&mut self, call: LlmToolCall, coordinator: &mut Coordinator) {
        coordinator.stream_tool_call_ids.push(call.id.clone());
        let preview_index = self.tool_calls.len() as u32;
        if let Some((existing_id, existing_name, existing_args)) =
            self.tool_call_previews.get_mut(&preview_index)
        {
            if !call.id.is_empty() {
                *existing_id = call.id.clone();
            }
            if existing_name.is_empty() && !call.name.is_empty() {
                *existing_name = call.name.clone();
            }
            *existing_args = call.arguments.clone();
            if let Some(ref cb) = coordinator.tool_preview_callback {
                cb(
                    existing_id.clone(),
                    existing_name.clone(),
                    call.arguments.clone(),
                );
            }
        }
        self.tool_calls.push(call);
    }

    fn handle_done(&mut self, usage: Option<LlmUsage>, coordinator: &Coordinator) {
        if let Some(u) = usage
            && (u.prompt_tokens > 0 || u.completion_tokens > 0)
        {
            self.prompt_eval_count = Some(u.prompt_tokens);
            self.eval_count = Some(u.completion_tokens);
            if let Some(ref cb) = coordinator.provider_event_callback {
                cb(LlmEvent::TurnMetrics {
                    prompt_tokens: u.prompt_tokens,
                    completion_tokens: u.completion_tokens,
                });
            }
        }
    }

    fn handle_retry_started(
        &mut self,
        attempt: u32,
        max_attempts: u32,
        delay_ms: u64,
        reason: String,
        coordinator: &Coordinator,
    ) {
        if let Some(ref cb) = coordinator.provider_event_callback {
            cb(LlmEvent::ProviderRetryStarted {
                attempt,
                max_attempts,
                delay_ms,
                reason,
            });
        }
    }

    fn handle_retry_finished(&mut self, success: bool, attempt: u32, coordinator: &Coordinator) {
        if let Some(ref cb) = coordinator.provider_event_callback {
            cb(LlmEvent::ProviderRetryFinished { success, attempt });
        }
    }
}

impl Coordinator {
    /// Creates a new `Coordinator` instance.
    pub fn new(
        provider: OpenAICompatibleProvider,
        model: String,
        history: Vec<LlmMessage>,
    ) -> Self {
        Self {
            model,
            provider,
            options: ProviderOptions::default(),
            history,
            tool_infos: Vec::default(),
            tools: HashMap::default(),
            think: None,
            event_callback: None,
            token_callback: None,
            thinking_callback: None,
            tool_call_callback: None,
            tool_preview_callback: None,
            provider_event_callback: None,
            context_window: None,
            system_prompt: None,
            real_history_tokens: None,
            initial_message_count: 0,
            pre_tool_content: String::new(),
            pre_tool_thinking: None,
            ephemeral_messages: Vec::new(),
            cancel_token: None,
            tool_call_counter: 0,
            react_retry_count: 0,
            stream_tool_call_ids: Vec::new(),
        }
    }

    /// Store streaming callbacks so they can be reused across ReAct rounds.
    ///
    /// `process_response` executes tools and then needs to continue streaming
    /// the next assistant turn. The callbacks are owned by the original caller
    /// (`core.rs`), so we box them here rather than threading them through
    /// every recursive call.
    fn set_streaming_callbacks(
        &mut self,
        on_token: impl Fn(String) + Send + Sync + 'static,
        on_thinking: impl Fn(String) + Send + Sync + 'static,
        on_tool_call: impl Fn() + Send + Sync + 'static,
        on_tool_call_preview: impl Fn(String, String, serde_json::Value) + Send + Sync + 'static,
        on_provider_event: impl Fn(LlmEvent) + Send + Sync + 'static,
    ) {
        self.token_callback = Some(Box::new(on_token));
        self.thinking_callback = Some(Box::new(on_thinking));
        self.tool_call_callback = Some(Box::new(on_tool_call));
        self.tool_preview_callback = Some(Box::new(on_tool_call_preview));
        self.provider_event_callback = Some(Box::new(on_provider_event));
    }

    fn compute_context_usage(
        &self,
        result: &str,
        prompt: &str,
    ) -> (ContextUsage, usize, usize, usize) {
        // Use ContextUsage as the single source of truth. Build a ContextUsage
        // from the API-reported prompt_tokens (or 0 if we don't have one yet)
        // and then `with_growth` for the new messages added in this request.
        // The final `total_tokens` is what was previously called
        // `total_after_add` — same value, just produced by the unified path.
        let pre_growth_base = self.real_history_tokens.unwrap_or(0);
        let base_usage = match self.real_history_tokens {
            Some(tokens) => ContextUsage::from_api_usage(tokens as u32, prompt, 0),
            None => {
                log::debug!("[check_and_handle] No real_history_tokens; using local estimate");
                ContextUsage {
                    system_tokens: 0, // diagnostic only — `total` is what matters
                    tools_tokens: 0,
                    history_tokens: pre_growth_base,
                    total_tokens: pre_growth_base,
                    source: crate::tokens::ContextSource::Estimated,
                }
            }
        };
        let usage = base_usage
            .with_growth(&self.history[self.initial_message_count..])
            .with_tool_result(result);

        // growth_tokens / result_tokens are kept only for the diagnostic
        // log lines below (which print them separately).
        let growth_tokens = usage
            .history_tokens
            .saturating_sub(base_usage.history_tokens);
        let result_tokens = usage.total_tokens - base_usage.total_tokens - growth_tokens;

        (usage, base_usage.total_tokens, growth_tokens, result_tokens)
    }

    fn compute_diagnostic_tool_tokens(&self) -> usize {
        // Tool definitions (each tool: name + description + parameters + overhead)
        // NOTE: These are already included in base_tokens from Ollama's prompt_eval_count
        // We calculate them separately only for diagnostic purposes
        self.tool_infos
            .iter()
            .map(|info| {
                let name_tokens = estimate_tokens(&info.function.name);
                let desc_tokens = estimate_tokens(&info.function.description);
                let params_tokens = estimate_tokens(
                    &serde_json::to_string(&info.function.parameters).unwrap_or_else(|e| {
                        // Every eprintln! in production code MUST have a
                        // corresponding log::warn! (AGENTS.md steering rule).
                        // Here the equivalent is `unwrap_or_default` for
                        // serializing tool parameters for token estimation;
                        // log the failure so it's not silent.
                        log::warn!("Failed to serialize tool parameters for token estimation: {e}");
                        String::new()
                    }),
                );
                name_tokens + desc_tokens + params_tokens + MESSAGE_OVERHEAD
            })
            .sum()
    }

    #[allow(clippy::too_many_arguments)]
    fn log_inter_tool_check(
        &self,
        usage: &ContextUsage,
        base_tokens: usize,
        growth_tokens: usize,
        tool_tokens: usize,
        system_tokens: usize,
        result_tokens: usize,
        total: usize,
        ctx_window: usize,
        compaction_buffer: usize,
    ) {
        let all_messages = self.history.len();
        let growth_messages = &self.history[self.initial_message_count..];

        // Format token values: show as raw number if < 1000, otherwise as NK
        fn fmt_tokens(v: usize) -> String {
            if v >= 1000 {
                format!("{}K", v / 1000)
            } else {
                format!("{}", v)
            }
        }

        // Debug log (only when debug enabled)
        log::debug!("[INTER-TOOL-CHECK-DETAILS]");
        log::debug!(
            "  base_tokens={} (from the LLM server, includes sys+tools+history)",
            base_tokens
        );
        log::debug!("  initial_message_count={}", self.initial_message_count);
        log::debug!("  all_messages={}", all_messages);
        log::debug!(
            "  growth_messages={} (new this request)",
            growth_messages.len()
        );
        log::debug!("  growth_tokens={} (estimated)", growth_tokens);
        log::debug!(
            "  tool_tokens={} (diagnostic, already in base)",
            tool_tokens
        );
        log::debug!(
            "  system_tokens={} (diagnostic, already in base)",
            system_tokens
        );
        log::debug!("  result_tokens={} (current tool result)", result_tokens);
        log::debug!(
            "[INTER-TOOL-CHECK] total={}/{} remaining={} buffer={}",
            fmt_tokens(total),
            fmt_tokens(ctx_window),
            fmt_tokens(ctx_window.saturating_sub(total)),
            fmt_tokens(compaction_buffer)
        );
        let _ = usage;
    }

    fn emergency_truncate(
        &self,
        result: String,
        total_after_add: usize,
        base_tokens: usize,
        growth_tokens: usize,
        ctx_window: usize,
    ) -> Option<ContextCheckResult> {
        if !is_emergency_context(total_after_add, ctx_window) {
            return None;
        }

        let available = calculate_available_budget(base_tokens + growth_tokens, ctx_window);
        let original_tokens = estimate_tokens(&result);
        let truncated = truncate_to_budget(&result, available);
        let truncated_tokens = estimate_tokens(&truncated);
        let reduction = original_tokens.saturating_sub(truncated_tokens);

        // Only show truncation warning if significant reduction
        if reduction > 100 || (original_tokens > 1000 && reduction * 100 / original_tokens > 10) {
            log::warn!(
                "[EMERGENCY] Context at {}% ({} tokens). Truncated tool result: {} → {} tokens",
                (total_after_add) * 100 / ctx_window,
                total_after_add,
                original_tokens,
                truncated_tokens
            );
        }

        Some(ContextCheckResult {
            result: truncated,
            is_near_limit: true,
            was_truncated: reduction > 0,
            tokens_used: total_after_add,
            needs_compaction: false,
        })
    }

    fn preemptive_truncate(
        &self,
        result: String,
        total_after_add: usize,
        ctx_window: usize,
    ) -> Option<ContextCheckResult> {
        // Defensive pre-truncation for tool results.
        //
        // `estimate_tokens` (in src/tokens.rs) uses a word-based heuristic
        // (~0.75 words/token, GPT-style) which UNDERCOUNTS by 30-50% vs
        // real model tokenizers (Llama, Mistral, Qwen) for mixed content
        // (code, JSON, non-English text, tool results). Empirically: we
        // estimated 27K tokens for a request the model counted as 40K.
        //
        // By the time `is_emergency_context` triggers (95% of ctx_window)
        // we are ALREADY overflowing the real tokenizer's count.
        // Preemptively truncate at 75% of the ESTIMATE so there's headroom
        // for the real tokenizer to be ~33% higher and still fit.
        //
        // TODO: A real tokenizer would give 100%
        // accuracy and let us size to the actual budget. Two options:
        //   1. tiktoken-rs (GPT-style BPE) — ~5MB binary, ~100ms load.
        //      Doesn't match Llama/Mistral/Qwen tokenizers 100%.
        //   2. Ollama's /api/tokenize endpoint — model-specific, no
        //      binary bloat, but adds HTTP RTT on the compaction path.
        // Deferred until we have a clearer accuracy-vs-complexity trade-off
        // from real-world data.
        if total_after_add < ctx_window.saturating_mul(3) / 4 {
            return None;
        }

        let target = ctx_window.saturating_mul(70) / 100; // 70% of ctx_window
        let excess = total_after_add.saturating_sub(target);
        let available = estimate_tokens(&result).saturating_sub(excess);
        let original_tokens = estimate_tokens(&result);
        let truncated = truncate_to_budget(&result, available);
        let truncated_tokens = estimate_tokens(&truncated);
        let reduction = original_tokens.saturating_sub(truncated_tokens);

        if reduction > 100 || (original_tokens > 1000 && reduction * 100 / original_tokens > 10) {
            log::warn!(
                "[PREEMPTIVE] Estimated context at {}% ({} tokens), \
                 truncated tool result to leave headroom for real tokenizer: \
                 {} → {} tokens",
                (total_after_add) * 100 / ctx_window,
                total_after_add,
                original_tokens,
                truncated_tokens,
            );
        }

        Some(ContextCheckResult {
            result: truncated,
            is_near_limit: true,
            was_truncated: reduction > 0,
            tokens_used: total_after_add,
            needs_compaction: false,
        })
    }

    fn compaction_check(
        &self,
        result: String,
        total_after_add: usize,
        base_tokens: usize,
        ctx_window: usize,
    ) -> Option<ContextCheckResult> {
        let remaining = ctx_window.saturating_sub(total_after_add);
        let (_, compaction_buffer, _, _) = calculate_thresholds(ctx_window);

        if remaining >= compaction_buffer {
            return None;
        }

        // Only trigger compaction if there's history to compact
        // base_tokens == 0 means fresh session with no messages to summarize
        if base_tokens == 0 {
            // Fresh session - nothing to compact, just proceed
            // Context will grow as conversation proceeds, future requests will have base > 0
            log::debug!(
                "[INTER-TOOL] Fresh session (base=0), nothing to compact. Proceeding... ({}K/{}K)",
                total_after_add / 1000,
                ctx_window / 1000
            );
            return Some(ContextCheckResult {
                result,
                is_near_limit: true,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: false,
            });
        }

        log::warn!(
            "⏳ [INTER-TOOL] Context: {}K/{}K ({}% used, {}K remaining). Buffer: {}K. NEEDS COMPACTION.",
            total_after_add / 1000,
            ctx_window / 1000,
            (total_after_add * 100) / ctx_window,
            remaining / 1000,
            compaction_buffer / 1000
        );

        Some(ContextCheckResult {
            result,
            is_near_limit: true,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: true,
        })
    }

    fn inter_tool_warning(
        &self,
        result: String,
        total_after_add: usize,
        ctx_window: usize,
    ) -> Option<ContextCheckResult> {
        if !needs_inter_tool_compaction(total_after_add, ctx_window) {
            return None;
        }

        log::debug!(
            "[INFO] Context at {}% ({} tokens). Inter-tool warning.",
            (total_after_add) * 100 / ctx_window,
            total_after_add
        );

        Some(ContextCheckResult {
            result,
            is_near_limit: false,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: false,
        })
    }

    /// Check context overflow and handle truncation if needed
    ///
    /// Returns a ContextCheckResult with the (possibly truncated) result and status flags.
    fn check_and_handle_context_overflow(&self, result: String) -> ContextCheckResult {
        let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) else {
            log::debug!("check_and_handle_context_overflow: no context_window or system_prompt");
            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: 0,
                needs_compaction: false,
            };
        };

        // Calculate total tokens:
        // 1. real_history_tokens: Base from session (Ollama's prompt_eval_count) - EXACT
        // 2. growth_tokens: New messages during this request (assistant + tool results) - ESTIMATED
        // 3. system_tokens: System prompt
        // 4. tool_tokens: Tool definitions
        // 5. result_tokens: Current tool result being processed

        let (usage, base_tokens, growth_tokens, result_tokens) =
            self.compute_context_usage(&result, prompt);
        let total_after_add = usage.total_tokens;

        let tool_tokens = self.compute_diagnostic_tool_tokens();
        let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;

        let (_, compaction_buffer, _, _) = calculate_thresholds(ctx_window);

        self.log_inter_tool_check(
            &usage,
            base_tokens,
            growth_tokens,
            tool_tokens,
            system_tokens,
            result_tokens,
            total_after_add,
            ctx_window,
            compaction_buffer,
        );

        if let Some(result) = self.emergency_truncate(
            result.clone(),
            total_after_add,
            base_tokens,
            growth_tokens,
            ctx_window,
        ) {
            return result;
        }

        if let Some(result) = self.preemptive_truncate(result.clone(), total_after_add, ctx_window)
        {
            return result;
        }

        if let Some(result) =
            self.compaction_check(result.clone(), total_after_add, base_tokens, ctx_window)
        {
            return result;
        }

        if let Some(result) = self.inter_tool_warning(result.clone(), total_after_add, ctx_window) {
            return result;
        }

        ContextCheckResult {
            result,
            is_near_limit: false,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: false,
        }
    }

    /// Set the context window size for overflow detection
    pub fn context_window(mut self, context_window: usize) -> Self {
        self.context_window = Some(context_window);
        self
    }

    /// Set the system prompt for token estimation
    pub fn system_prompt(mut self, system_prompt: String) -> Self {
        self.system_prompt = Some(system_prompt);
        self
    }

    /// Set the real history token count from Ollama's prompt_eval_count.
    /// This should ALWAYS be used when available for accurate overflow detection.
    /// Estimation is a fallback when real tokens are not available.
    pub fn real_history_tokens(mut self, tokens: usize) -> Self {
        self.real_history_tokens = Some(tokens);
        self
    }

    /// Add a tool to the coordinator.
    ///
    /// The bound is `crate::tools::Tool` (our own trait, generated by
    /// `#[sprachspiel::tool]`).
    pub fn add_tool<T: crate::tools::Tool + 'static>(mut self, tool: T) -> Self {
        self.tool_infos.push(ToolInfo::new::<T::Params, T>());
        self.tools.insert(T::name().to_string(), Box::new(tool));
        self
    }

    /// Set model options
    pub fn options(mut self, options: ProviderOptions) -> Self {
        self.options = options;
        self
    }

    /// Set think mode
    pub fn think(mut self, think: impl Into<bool>) -> Self {
        self.think = Some(think.into());
        self
    }

    /// Set event callback for receiving intermediate content and events
    pub fn on_event(mut self, callback: impl Fn(ChatEvent) + Send + Sync + 'static) -> Self {
        self.event_callback = Some(Box::new(callback));
        self
    }

    /// Extract accumulated pre-tool content
    ///
    /// Returns the content generated before tool calls and clears the accumulator.
    /// This should be called after `chat()` returns to get any pre-tool content.
    pub fn take_pre_tool_content(&mut self) -> Option<PreToolContent> {
        if self.pre_tool_content.is_empty() {
            return None;
        }
        Some(PreToolContent {
            content: std::mem::take(&mut self.pre_tool_content),
            thinking: self.pre_tool_thinking.take(),
        })
    }

    /// Add an ephemeral message (not persisted to history)
    ///
    /// Ephemeral messages are prepended to requests but never saved.
    /// Used for continuation prompts after context compaction.
    pub fn push_ephemeral(&mut self, message: LlmMessage) {
        self.ephemeral_messages.push(message);
    }

    /// Set the cancellation token for tool loop interruption.
    ///
    /// When the token is cancelled, the tool execution loop stops after
    /// the current tool finishes and returns an error. The caller
    /// (event loop) interprets this as user-initiated cancellation.
    pub fn cancel_token(mut self, token: tokio_util::sync::CancellationToken) -> Self {
        self.cancel_token = Some(token);
        self
    }

    /// Emit an event if callback is set
    fn emit_event(&self, event: ChatEvent) {
        if let Some(ref callback) = self.event_callback {
            callback(event);
        }
    }

    /// Send a chat message and process tool calls with event emission
    pub async fn chat(&mut self, messages: Vec<LlmMessage>) -> Result<LlmResponse, ProviderError> {
        for m in &messages {
            log::debug!("Hit {} with:", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        // Push initial messages to history
        for m in messages.clone() {
            self.history.push(m);
        }

        self.initial_message_count = self.history.len();

        let resp = self
            .provider
            .chat(
                &self.model,
                self.build_request_messages(),
                self.tool_infos.clone(),
                self.options.clone(),
            )
            .await?;

        self.process_response(resp, false).await
    }

    /// Send a chat message with streaming and process tool calls.
    ///
    /// This is the streaming equivalent of `chat()`. Instead of waiting for
    /// the full response, it streams token chunks through the provided
    /// `on_token` callback. When the stream completes:
    /// - If no tool calls: returns the accumulated response
    /// - If tool calls: enters the non-streaming tool loop (since tool
    ///   execution must complete before the next request)
    ///
    /// The `on_token` callback is called with each content token chunk.
    /// The `on_thinking` callback is called with each thinking chunk.
    /// Both callbacks must be `Send + Sync` for use in async tasks.
    ///
    /// If `cancel_token` is provided and becomes cancelled during streaming,
    /// the stream is aborted and the accumulated partial content is returned
    /// as the response.
    #[expect(clippy::too_many_arguments)] // callback set is intentionally explicit
    pub async fn chat_stream(
        &mut self,
        messages: Vec<LlmMessage>,
        on_token: impl Fn(String) + Send + Sync + 'static,
        on_thinking: impl Fn(String) + Send + Sync + 'static,
        on_tool_call: impl Fn() + Send + Sync + 'static,
        on_tool_call_preview: impl Fn(String, String, serde_json::Value) + Send + Sync + 'static,
        on_provider_event: impl Fn(LlmEvent) + Send + Sync + 'static,
        cancel_token: Option<tokio_util::sync::CancellationToken>,
    ) -> Result<LlmResponse, ProviderError> {
        for m in &messages {
            log::debug!("Hit {} with (stream):", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        // Push initial messages to history
        for m in messages.clone() {
            self.history.push(m);
        }

        self.initial_message_count = self.history.len();

        // Store callbacks for reuse in later ReAct rounds.
        self.set_streaming_callbacks(
            on_token,
            on_thinking,
            on_tool_call,
            on_tool_call_preview,
            on_provider_event,
        );
        self.cancel_token = cancel_token;

        let response = self.stream_turn().await?;

        let mut current_response = response;
        loop {
            if current_response.tool_calls.is_none()
                || current_response
                    .tool_calls
                    .as_ref()
                    .map(|tc| tc.is_empty())
                    .unwrap_or(true)
            {
                return Ok(current_response);
            }
            current_response = self.process_response(current_response, true).await?;
        }
    }

    /// Internal streaming turn handler. Calls `LlmProvider::chat_stream`
    /// and accumulates events into an `LlmResponse`.
    async fn stream_turn(&mut self) -> Result<LlmResponse, ProviderError> {
        let messages = self.build_request_messages();
        let tools = self.tool_infos.clone();
        let options = self.options.clone();
        let mut stream = self
            .provider
            .chat_stream(&self.model, messages, tools, options)
            .await?;

        let mut state = StreamTurnState::new();
        self.stream_tool_call_ids.clear();

        use futures::StreamExt;

        while let Some(event_result) = stream.next().await {
            if let Some(ref ct) = self.cancel_token
                && ct.is_cancelled()
            {
                log::debug!("Stream cancelled by user");
                break;
            }

            match event_result {
                Ok(event) => match event {
                    LlmStreamEvent::TextDelta { delta } => {
                        state.handle_text_delta(delta, self);
                    }
                    LlmStreamEvent::ThinkingDelta { delta } => {
                        state.handle_thinking_delta(delta, self);
                    }
                    LlmStreamEvent::ToolCallStart { index, id, name } => {
                        state.handle_tool_call_start(index, id, name, self);
                    }
                    LlmStreamEvent::ToolCallDelta {
                        index,
                        id,
                        name_delta,
                        argument_delta,
                    } => {
                        state.handle_tool_call_delta(index, id, name_delta, argument_delta, self);
                    }
                    LlmStreamEvent::ToolCallEnd { call, .. } => {
                        state.handle_tool_call_end(call, self);
                    }
                    LlmStreamEvent::Done { reason: _, usage } => {
                        state.handle_done(usage, self);
                    }
                    LlmStreamEvent::ProviderRetryStarted {
                        attempt,
                        max_attempts,
                        delay_ms,
                        reason,
                    } => {
                        state.handle_retry_started(attempt, max_attempts, delay_ms, reason, self);
                    }
                    LlmStreamEvent::ProviderRetryFinished { success, attempt } => {
                        state.handle_retry_finished(success, attempt, self);
                    }
                    _ => {}
                },
                Err(err) => {
                    log::error!("Stream error in coordinator: {err}");
                    return Err(err);
                }
            }
        }

        Ok(LlmResponse {
            model: self.model.clone(),
            content: state.full_content,
            tool_calls: if state.tool_calls.is_empty() {
                None
            } else {
                Some(state.tool_calls)
            },
            thinking: state.full_thinking,
            done_reason: Some("stop".to_string()),
            eval_count: state.eval_count,
            prompt_eval_count: state.prompt_eval_count,
        })
    }

    /// Build messages for a provider request: ephemeral first, then history.
    fn build_request_messages(&self) -> Vec<LlmMessage> {
        let mut messages = Vec::with_capacity(self.ephemeral_messages.len() + self.history.len());
        messages.extend(self.ephemeral_messages.iter().cloned());
        messages.extend(self.history.iter().cloned());
        messages
    }

    /// Process response, handling tool calls with event emission.
    ///
    /// `already_streamed` should be `true` when the content was already
    /// streamed via `chat_stream()` — this prevents emitting an extra
    /// `PreToolContent` event that would duplicate the text. All ReAct turns
    /// stream, so the only remaining non-streaming call site is `chat()`
    /// (terminal/CLI query path).
    async fn process_response(
        &mut self,
        resp: LlmResponse,
        already_streamed: bool,
    ) -> Result<LlmResponse, ProviderError> {
        let has_tool_calls = resp
            .tool_calls
            .as_ref()
            .map(|tc| !tc.is_empty())
            .unwrap_or(false);

        if has_tool_calls {
            let has_content = !resp.content.trim().is_empty();
            let has_thinking = resp.thinking.is_some();

            if has_content || has_thinking {
                if already_streamed {
                    if !resp.content.trim().is_empty() {
                        if !self.pre_tool_content.is_empty() {
                            self.pre_tool_content.push_str("\n\n");
                        }
                        self.pre_tool_content.push_str(&resp.content);
                    }
                    if self.pre_tool_thinking.is_none() {
                        self.pre_tool_thinking = resp.thinking.clone();
                    }
                }

                self.emit_event(ChatEvent::PreToolContent {
                    content: resp.content.clone(),
                    thinking: resp.thinking.clone(),
                });
            }

            // Build assistant message with tool_calls for history
            let mut sanitized_tool_calls = resp.tool_calls.clone().unwrap_or_default();
            let mut had_invalid_args = false;
            for tc in &mut sanitized_tool_calls {
                if matches!(tc.arguments, serde_json::Value::String(_)) {
                    log::warn!(
                        "Sanitizing invalid tool call arguments for '{}': \
                         replacing Value::String (malformed JSON) with empty Object",
                        tc.name
                    );
                    tc.arguments = serde_json::Value::Object(serde_json::Map::new());
                    had_invalid_args = true;
                }
            }
            if had_invalid_args {
                log::debug!(
                    "Sanitized {} tool call(s) with invalid arguments \
                     before persisting to history",
                    sanitized_tool_calls.len()
                );
            }

            let assistant_msg = LlmMessage {
                role: LlmRole::Assistant,
                content: resp.content.clone(),
                tool_calls: Some(sanitized_tool_calls),
                images: None,
                audio: None,
                thinking: resp.thinking.clone(),
                name: None,
                tool_call_id: None,
            };
            self.history.push(assistant_msg);

            let mut tools_executed = Vec::new();

            for (call_idx, call) in resp.tool_calls.unwrap_or_default().into_iter().enumerate() {
                if let Some(ref ct) = self.cancel_token
                    && ct.is_cancelled()
                {
                    log::debug!(
                        "Tool loop cancelled by user after {} tools",
                        tools_executed.len()
                    );
                    return Err(ProviderError::Other(CANCELLED_BY_USER.to_string()));
                }

                let tool_name = call.name.clone();
                let args = call.arguments.clone();
                self.tool_call_counter += 1;
                let tool_call_id = match self.stream_tool_call_ids.get(call_idx) {
                    Some(stream_id) if !stream_id.is_empty() => stream_id.clone(),
                    _ => format!("{tool_name}_{}", self.tool_call_counter),
                };

                log::debug!("Tool call: {} (id={})", tool_name, tool_call_id);

                self.emit_event(ChatEvent::ToolExecutionStarted {
                    tool_call_id: tool_call_id.clone(),
                    name: tool_name.clone(),
                    args: args.clone(),
                });

                let Some(tool) = self.tools.get_mut(&tool_name) else {
                    log::debug!(
                        "Unknown tool '{}'. Available: {}",
                        tool_name,
                        self.tools.keys().cloned().collect::<Vec<_>>().join(", ")
                    );
                    return Err(ProviderError::Other(format!("unknown tool: {tool_name}")));
                };

                let result = match tool.call(args.clone()).await {
                    Ok(result) => {
                        let is_error = is_tool_error(&result);
                        self.emit_event(ChatEvent::ToolExecutionFinished {
                            tool_call_id: tool_call_id.clone(),
                            result: result.clone(),
                            is_error,
                        });
                        result
                    }
                    Err(e) => {
                        log::warn!("Tool '{}' execution failed: {e}", tool_name);
                        log::debug!(
                            "  Arguments: {}",
                            serde_json::to_string(&args).unwrap_or_else(|_| args.to_string())
                        );
                        let error_msg = format!(
                            "Error executing tool '{tool_name}': {e}. \
                             Please try again with different arguments or use a different approach."
                        );
                        self.emit_event(ChatEvent::ToolExecutionFinished {
                            tool_call_id: tool_call_id.clone(),
                            result: error_msg.clone(),
                            is_error: true,
                        });
                        self.history.push(LlmMessage::tool(error_msg));
                        tools_executed.push(tool_name.clone());
                        continue;
                    }
                };

                log::debug!("Tool response: {}", &result);

                let check_result = self.check_and_handle_context_overflow(result);

                if check_result.needs_compaction {
                    self.history.push(LlmMessage::tool(check_result.result));
                    tools_executed.push(tool_name.clone());

                    self.emit_event(ChatEvent::ContextNeedsCompaction {
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                        tools_executed: tools_executed.clone(),
                    });

                    let tools_str = tools_executed.join(", ");
                    return Err(ProviderError::Other(format!(
                        "CONTEXT_NEEDS_COMPACT:{}:{}:{}",
                        check_result.tokens_used,
                        self.context_window.unwrap_or(0),
                        tools_str
                    )));
                }

                if check_result.was_truncated {
                    let result_tokens = estimate_tokens(&check_result.result);
                    self.emit_event(ChatEvent::ContextTruncated {
                        tool_name: tool_name.clone(),
                        original_tokens: check_result.tokens_used,
                        new_tokens: result_tokens,
                        context_window: self.context_window.unwrap_or(0),
                    });
                } else if check_result.is_near_limit {
                    self.emit_event(ChatEvent::ContextNearLimit {
                        tool_name: tool_name.clone(),
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                    });
                }

                self.history.push(LlmMessage::tool(check_result.result));
                tools_executed.push(tool_name);
            }

            Box::pin(self.process_next_stream()).await
        } else {
            let assistant_msg = LlmMessage {
                role: LlmRole::Assistant,
                content: resp.content.clone(),
                tool_calls: resp.tool_calls.clone(),
                images: None,
                audio: None,
                thinking: resp.thinking.clone(),
                name: None,
                tool_call_id: None,
            };
            self.history.push(assistant_msg);

            Ok(resp)
        }
    }

    /// Process next response after tool calls, using streaming.
    async fn process_next_stream(&mut self) -> Result<LlmResponse, ProviderError> {
        if let Some(ref ct) = self.cancel_token
            && ct.is_cancelled()
        {
            log::debug!("process_next_stream cancelled by user");
            return Err(ProviderError::Other(CANCELLED_BY_USER.to_string()));
        }

        // Context overflow check
        if let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) {
            let usage = match self.real_history_tokens {
                Some(tokens) => ContextUsage::from_api_usage(tokens as u32, prompt, 0),
                None => {
                    log::debug!(
                        "[process_next_stream] No real_history_tokens; falling back to estimate"
                    );
                    let messages = &self.history;
                    let system = estimate_tokens(prompt) + MESSAGE_OVERHEAD;
                    let history: usize = messages
                        .iter()
                        .map(|m| estimate_tokens(&m.content) + MESSAGE_OVERHEAD)
                        .sum();
                    ContextUsage {
                        system_tokens: system,
                        tools_tokens: 0,
                        history_tokens: history,
                        total_tokens: system + history,
                        source: crate::tokens::ContextSource::Estimated,
                    }
                }
            };

            let (_, _, _, emergency_threshold) = calculate_thresholds(ctx_window);
            let threshold = ctx_window.saturating_sub(emergency_threshold);

            if usage.total_tokens > threshold {
                let msg = format!(
                    "Context overflow during tool execution: {} tokens used, {} available. Use /compact to reduce context.",
                    usage.total_tokens, ctx_window
                );
                return Err(ProviderError::Other(msg));
            }
        }

        let response = match self.stream_turn().await {
            Ok(resp) => resp,
            Err(e) => match &e {
                ProviderError::Timeout(_) => {
                    self.react_retry_count += 1;
                    if self.react_retry_count > 3 {
                        log::warn!(
                            "Stream timed out {} times in ReAct loop — \
                                 giving up to avoid infinite loop",
                            self.react_retry_count
                        );
                        return Err(e);
                    }
                    log::debug!(
                        "Stream timeout in ReAct loop (attempt {}/3): {e} — retrying",
                        self.react_retry_count
                    );
                    let recovery_msg = "Error: The request timed out after the provider accepted \
                             the connection but did not produce any output. \
                             The provider may be under load or processing a large \
                             context. Please continue from where you left off.";
                    self.history
                        .push(LlmMessage::tool(recovery_msg.to_string()));
                    self.stream_turn().await?
                }
                ProviderError::Api { status: 400, body }
                    if body.contains("invalid tool call arguments") || body.contains("tool") =>
                {
                    self.react_retry_count += 1;
                    if self.react_retry_count > 3 {
                        log::warn!(
                            "Provider rejected tool call arguments {} times — \
                                 giving up to avoid infinite loop",
                            self.react_retry_count
                        );
                        return Err(e);
                    }
                    log::debug!(
                        "Provider rejected tool call arguments (attempt {}/3) — \
                             pushing error as tool message and retrying",
                        self.react_retry_count
                    );
                    let recovery_msg = format!(
                        "Error: The provider rejected the tool call arguments \
                             as invalid. This usually means the arguments were \
                             malformed JSON or had missing/invalid fields. \
                             Please try again with valid arguments.\n\n\
                             Provider error: {e}"
                    );
                    self.history.push(LlmMessage::tool(recovery_msg));
                    self.stream_turn().await?
                }
                _ => return Err(e),
            },
        };

        self.react_retry_count = 0;

        let has_tool_calls = response
            .tool_calls
            .as_ref()
            .map(|tc| !tc.is_empty())
            .unwrap_or(false);

        if has_tool_calls {
            self.process_response(response, true).await
        } else {
            Ok(response)
        }
    }
}

/// Heuristic: detect whether a tool result string represents an error.
///
/// Tools follow the convention "always return Ok(String)" (AGENTS.md: "Tools
/// must NEVER crash"). Error messages use various prefixes depending on the
/// tool and the error path (validate_path, blocklist, file ops, etc.).
/// This function checks the common error prefixes so the coordinator can flag
/// `is_error=true` and the TUI can show a visual indicator (✗ prefix).
fn is_tool_error(result: &str) -> bool {
    // Trim leading whitespace — some tools may have leading spaces.
    let trimmed = result.trim_start();
    // Common error prefixes used across all tools.
    trimmed.starts_with("Error:")
        || trimmed.starts_with("Access denied:")
        || trimmed.starts_with("FILE NOT FOUND:")
        || trimmed.starts_with("NOT A FILE:")
        || trimmed.starts_with("NOT A DIRECTORY:")
        || trimmed.starts_with("BLOCKED:")
        || trimmed.starts_with("Error executing tool")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_continuation_tag_basic() {
        let content = r#"I've analyzed the first part. Let me continue.

<continuation_needed>
Reasoning paused: Analyzed file structure
Next step: Examine the main function
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Analyzed file structure");
        assert_eq!(tag.next_step, "Examine the main function");
        assert!(cleaned.contains("I've analyzed the first part"));
        assert!(!cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_multiline() {
        let content = r#"Some response here.

<continuation_needed>
Reasoning paused: Completed step 1
Next step: Process step 2
</continuation_need>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none(), "Should not parse without closing tag");
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_in_code_block() {
        let content = r#"Here's an example:

```
<continuation_needed>
Reasoning paused: In code block
Next step: Should not parse
</continuation_needed>
```

This should not be parsed as a continuation tag."#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(
            tag.is_none(),
            "Tags inside code blocks should not be parsed"
        );
        assert!(cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_empty_fields() {
        let content = r#"<continuation_needed>
Reasoning paused:
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Empty fields should return None
        assert!(tag.is_none());
    }

    #[test]
    fn test_parse_continuation_tag_partial_fields() {
        let content = r#"<continuation_needed>
Reasoning paused: Half way through analysis
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Should still parse if at least one field is filled
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Half way through analysis");
        assert!(tag.next_step.is_empty());
    }

    #[test]
    fn test_parse_continuation_tag_no_tag() {
        let content = "This is a normal response without any continuation tag.";

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none());
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_nested_tags() {
        // Nested tags shouldn't happen in practice, but if they do,
        // we parse from first open to first close and take the last matching values
        let content = r#"<continuation_needed>
Reasoning paused: First level
Next step: Second level
<continuation_needed>
Reasoning paused: Nested
Next step: Should ignore
</continuation_needed>
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // We find the first </continuation_needed> (after "ignore")
        // and parse the content between, which includes all lines
        // The last matching field values win
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Nested"); // Last "Reasoning paused:" wins
        assert_eq!(tag.next_step, "Should ignore"); // Last "Next step:" wins
    }

    #[test]
    fn test_is_tool_error_detects_common_prefixes() {
        assert!(is_tool_error("Error: File not found"));
        assert!(is_tool_error("Access denied: path not accessible"));
        assert!(is_tool_error("FILE NOT FOUND: '/tmp/missing.txt'. ..."));
        assert!(is_tool_error("NOT A FILE: '/tmp'. ..."));
        assert!(is_tool_error("NOT A DIRECTORY: '/tmp/file'. ..."));
        assert!(is_tool_error("BLOCKED: '/tmp/.env'. ..."));
        assert!(is_tool_error("Error executing tool 'read_file': ..."));
        // Leading whitespace is trimmed
        assert!(is_tool_error("  Error: indented"));
        // Success cases are NOT errors
        assert!(!is_tool_error("file1.txt\nfile2.txt"));
        assert!(!is_tool_error("Contents of the file..."));
        assert!(!is_tool_error("Task 1 marked as in_progress"));
        assert!(!is_tool_error(""));
    }

    #[test]
    fn test_sanitizes_invalid_tool_call_arguments() {
        use crate::provider::types::{LlmMessage, LlmRole, LlmToolCall};

        let calls = vec![
            LlmToolCall {
                id: "call_1".to_string(),
                name: "todo_add".to_string(),
                arguments: serde_json::Value::String(
                    r#"{"description":"task1","priority":"high"}{"description":"task2"}"#
                        .to_string(),
                ),
            },
            LlmToolCall {
                id: "call_2".to_string(),
                name: "read_file".to_string(),
                arguments: serde_json::json!({"path": "test.txt"}),
            },
        ];

        let mut sanitized = calls.clone();
        for tc in &mut sanitized {
            if matches!(tc.arguments, serde_json::Value::String(_)) {
                tc.arguments = serde_json::Value::Object(serde_json::Map::new());
            }
        }

        assert_eq!(
            sanitized[0].arguments,
            serde_json::Value::Object(serde_json::Map::new()),
            "Invalid Value::String args should be sanitized to empty Object"
        );
        assert_eq!(
            sanitized[1].arguments,
            serde_json::json!({"path": "test.txt"}),
            "Valid args should be preserved"
        );
    }
}
