//! Custom Coordinator with callbacks for intermediate content
//!
//! This is our own implementation that provides:
//! - Pre-tool content callbacks (content before tool calls)
//! - Thinking content callbacks
//! - Full control over tool execution flow
//! - Inter-tool context overflow detection

use std::{collections::HashMap, future::Future, pin::Pin};

use ollama_rs::re_exports::serde::{Deserialize, Serialize, de::DeserializeOwned};
use ollama_rs::{
    Ollama,
    generation::{
        chat::{ChatMessage, ChatMessageResponse, MessageRole, request::ChatMessageRequest},
        parameters::{FormatType, KeepAlive, ThinkType},
        tools::Tool,
    },
    history::ChatHistory,
    models::ModelOptions,
    re_exports::schemars::{JsonSchema, Schema, generate::SchemaSettings},
};
use serde_json::Value;

use crate::context_overflow::{
    calculate_available_budget, estimate_chat_messages_tokens,
    is_emergency_context, needs_inter_tool_compaction,
    COMPACTION_BUFFER, EMERGENCY_BUFFER,
};
use crate::tokens::{estimate_tokens, MESSAGE_OVERHEAD};
use crate::utils::truncate_to_budget;

/// Result type for tool execution
pub type ToolResult = std::result::Result<String, Box<dyn std::error::Error + Send + Sync>>;

/// Trait to hold and call tools - our own implementation since ollama-rs's ToolHolder is private
pub trait ToolHolder: Send + Sync {
    fn call(
        &mut self,
        parameters: Value,
    ) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send + Sync>>;
}

impl<T: Tool> ToolHolder for T {
    fn call(
        &mut self,
        parameters: Value,
    ) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send + Sync>> {
        Box::pin(async move {
            // Handle different JSON formats that models might return
            let param_value =
                match serde_json::from_value::<ToolCallFunctionParser>(parameters.clone()) {
                    Ok(func) => func.arguments,
                    Err(_) => parameters,
                };

            let params: T::Params = serde_json::from_value(param_value)?;
            T::call(self, params).await
        })
    }
}

/// Helper struct for parsing tool call function JSON
#[derive(Deserialize)]
struct ToolCallFunctionParser {
    #[allow(dead_code)]
    name: String,
    arguments: Value,
}

/// Tool type enum
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CustomToolType {
    #[serde(rename_all(deserialize = "PascalCase"))]
    Function,
}

/// Tool function info
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolFunctionInfo {
    pub name: String,
    pub description: String,
    pub parameters: Schema,
}

/// Our own ToolInfo since ollama-rs's ToolInfo::new is private
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolInfo {
    #[serde(rename = "type")]
    pub tool_type: CustomToolType,
    pub function: CustomToolFunctionInfo,
}

impl CustomToolInfo {
    /// Create a new ToolInfo for a given Tool type
    pub fn new<P: DeserializeOwned + JsonSchema, T: Tool<Params = P>>() -> Self {
        let mut settings = SchemaSettings::draft07();
        settings.inline_subschemas = true;
        let generator = settings.into_generator();

        let parameters = generator.into_root_schema_for::<P>();

        Self {
            tool_type: CustomToolType::Function,
            function: CustomToolFunctionInfo {
                name: T::name().to_string(),
                description: T::description().to_string(),
                parameters,
            },
        }
    }
}

/// Pre-tool content accumulated during processing
///
/// Contains text generated by the assistant before tool calls,
/// which should be saved separately from the final response.
#[derive(Debug, Clone, Default)]
pub struct PreToolContent {
    /// Content generated before tool calls
    pub content: String,
    /// Thinking content (if any)
    pub thinking: Option<String>,
}

/// Continuation tag parsed from LLM response
///
/// When the LLM detects context is nearly full and needs to pause,
/// it emits this tag with checkpoint information for resumption.
#[derive(Debug, Clone)]
pub struct ContinuationTag {
    /// Where reasoning was paused
    pub paused_at: String,
    /// What the LLM was about to do next
    pub next_step: String,
}

/// Parse continuation tag from LLM response
///
/// Extracts the <continuation_needed> tag content and returns
/// both the cleaned response (without the tag) and the parsed tag.
///
/// Returns (cleaned_content, Some(tag)) if tag found and parsed,
/// or (original_content, None) if no tag or invalid.
pub fn parse_continuation_tag(content: &str) -> (String, Option<ContinuationTag>) {
    // Find the tag
    let start_tag = "<continuation_needed>";
    let end_tag = "</continuation_needed>";

    let start_pos = match content.find(start_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Check if tag is inside a code block (should NOT be parsed)
    let before_tag = &content[..start_pos];
    let code_block_count = before_tag.matches("```").count();
    if code_block_count % 2 == 1 {
        // Inside a code block, don't parse
        return (content.to_string(), None);
    }

    let end_pos = match content.find(end_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Extract tag content
    let tag_content = &content[start_pos + start_tag.len()..end_pos];

    // Parse fields
    let mut paused_at = String::new();
    let mut next_step = String::new();

    for line in tag_content.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("Reasoning paused:") {
            paused_at = value.trim().to_string();
        } else if let Some(value) = line.strip_prefix("Next step:") {
            next_step = value.trim().to_string();
        }
    }

    // Create cleaned content by removing the tag
    let cleaned = format!(
        "{}{}",
        &content[..start_pos],
        &content[end_pos + end_tag.len()..]
    );

    // Normalize whitespace in cleaned content
    let cleaned = cleaned.trim().to_string();

    // Require at least one field to be filled
    if paused_at.is_empty() && next_step.is_empty() {
        return (content.to_string(), None);
    }

    (
        cleaned,
        Some(ContinuationTag {
            paused_at,
            next_step,
        }),
    )
}

/// Event emitted during chat processing
#[derive(Debug, Clone)]
pub enum ChatEvent {
    /// Content generated before tool calls (often thinking/intro text)
    PreToolContent {
        content: String,
        thinking: Option<String>,
    },
    /// Tool call is about to be executed (fields kept for future use)
    #[allow(dead_code)]
    ToolCall {
        name: String,
        arguments: serde_json::Value,
    },
    /// Tool execution result
    /// Name field kept for future debugging use
    #[allow(dead_code)]
    ToolResult { name: String, result: String },
    /// Context is near limit after tool execution (inter-tool threshold)
    /// Indicates compaction may be needed before next tool
    ContextNearLimit {
        tool_name: String,
        tokens_used: usize,
        context_window: usize,
    },
    /// Context was truncated during tool execution (emergency threshold)
    /// Indicates last tool result was truncated to fit
    ContextTruncated {
        tool_name: String,
        original_tokens: usize,
        new_tokens: usize,
        context_window: usize,
    },
    /// Context needs compaction during tool execution (compaction threshold)
    /// Signals that tool execution should pause for compaction
    ContextNeedsCompaction {
        tokens_used: usize,
        context_window: usize,
        tools_executed: Vec<String>,
    },
}

/// Error type for coordinator operations during tool execution
#[derive(Debug)]
#[allow(dead_code)]
pub enum CoordinatorError {
    /// Context needs compaction before continuing
    /// Contains: (tokens_used, context_window, tools_executed)
    ContextNeedsCompact {
        tokens_used: usize,
        context_window: usize,
        tools_executed: Vec<String>,
    },
}

impl std::fmt::Display for CoordinatorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ContextNeedsCompact {
                tokens_used,
                context_window,
                tools_executed,
            } => {
                write!(
                    f,
                    "Context needs compaction: {} / {} tokens used, {} tools executed",
                    tokens_used,
                    context_window,
                    tools_executed.len()
                )
            }
        }
    }
}

impl std::error::Error for CoordinatorError {}

/// Result of checking context overflow after tool execution
struct ContextCheckResult {
    /// The result to use (possibly truncated)
    result: String,
    /// Whether context is near limit (inter-tool threshold)
    is_near_limit: bool,
    /// Whether result was truncated (emergency threshold)
    was_truncated: bool,
    /// Tokens used (for events)
    tokens_used: usize,
    /// Whether compaction is needed before continuing
    needs_compaction: bool,
}

/// A coordinator for managing chat interactions with event callbacks.
pub struct CustomCoordinator<C: ChatHistory> {
    model: String,
    ollama: Ollama,
    options: ModelOptions,
    history: C,
    tool_infos: Vec<CustomToolInfo>,
    tools: HashMap<String, Box<dyn ToolHolder>>,
    debug: bool,
    format: Option<FormatType>,
    keep_alive: Option<KeepAlive>,
    think: Option<ThinkType>,
    /// Callback for events
    event_callback: Option<Box<dyn Fn(ChatEvent) + Send + Sync>>,
    /// Context window size for overflow detection during tool execution
    context_window: Option<usize>,
    /// System prompt for token estimation
    system_prompt: Option<String>,
    /// Accumulated pre-tool content (text generated before tool calls)
    pre_tool_content: String,
    pre_tool_thinking: Option<String>,
    /// Ephemeral messages (not persisted to history)
    /// Used for continuation prompts after context compaction
    ephemeral_messages: Vec<ChatMessage>,
}

impl<C: ChatHistory> CustomCoordinator<C> {
    /// Creates a new `CustomCoordinator` instance.
    pub fn new(ollama: Ollama, model: String, history: C) -> Self {
        Self {
            model,
            ollama,
            options: ModelOptions::default(),
            history,
            tool_infos: Vec::default(),
            tools: HashMap::default(),
            debug: false,
            format: None,
            keep_alive: None,
            think: None,
            event_callback: None,
            context_window: None,
            system_prompt: None,
            pre_tool_content: String::new(),
            pre_tool_thinking: None,
            ephemeral_messages: Vec::new(),
        }
    }

    /// Check context overflow and handle truncation if needed
    ///
    /// Returns a ContextCheckResult with the (possibly truncated) result and status flags.
    fn check_and_handle_context_overflow(
        &self,
        _tool_name: &str,
        result: String,
    ) -> ContextCheckResult {
        let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) else {
            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: 0,
                needs_compaction: false,
            };
        };

        let history_tokens = estimate_chat_messages_tokens(&self.history.messages());
        let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;
        let result_tokens = estimate_tokens(&result);
        let total_after_add = history_tokens + system_tokens + result_tokens;

        if is_emergency_context(history_tokens + result_tokens, system_tokens, ctx_window) {
            let available = calculate_available_budget(history_tokens, system_tokens, ctx_window);

            if self.debug {
                eprintln!(
                    "\x1B[33m[WARN] Context emergency at {}% ({} tokens). Truncating result...\x1B[0m",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add
                );
            }

            let truncated = truncate_to_budget(&result, available);

            return ContextCheckResult {
                result: truncated,
                is_near_limit: true,
                was_truncated: true,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        let remaining = ctx_window.saturating_sub(total_after_add);
        if remaining < COMPACTION_BUFFER {
            if self.debug {
                eprintln!(
                    "\x1B[33m[INFO] Context at {}% ({} tokens, {}K remaining). Inter-tool compaction needed.\x1B[0m",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add,
                    remaining / 1000
                );
            }

            return ContextCheckResult {
                result,
                is_near_limit: true,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: true,
            };
        }

        if needs_inter_tool_compaction(history_tokens + result_tokens, system_tokens, ctx_window) {
            if self.debug {
                eprintln!(
                    "\x1B[33m[INFO] Context at {}% ({} tokens). Inter-tool warning.\x1B[0m",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add
                );
            }

            return ContextCheckResult {
                result,
                is_near_limit: true,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        ContextCheckResult {
            result,
            is_near_limit: false,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: false,
        }
    }

    /// Set the context window size for overflow detection
    pub fn context_window(mut self, context_window: usize) -> Self {
        self.context_window = Some(context_window);
        self
    }

    /// Set the system prompt for token estimation
    pub fn system_prompt(mut self, system_prompt: String) -> Self {
        self.system_prompt = Some(system_prompt);
        self
    }

    /// Add a tool to the coordinator
    pub fn add_tool<T: Tool + 'static>(mut self, tool: T) -> Self {
        self.tool_infos.push(CustomToolInfo::new::<T::Params, T>());
        self.tools.insert(T::name().to_string(), Box::new(tool));
        self
    }

    /// Set the format (for future use)
    #[allow(dead_code)]
    pub fn format(mut self, format: FormatType) -> Self {
        self.format = Some(format);
        self
    }

    /// Set model options
    pub fn options(mut self, options: ModelOptions) -> Self {
        self.options = options;
        self
    }

    /// Enable debug mode (for future use)
    #[allow(dead_code)]
    pub fn debug(mut self, debug: bool) -> Self {
        self.debug = debug;
        self
    }

    /// Set keep alive (for future use)
    #[allow(dead_code)]
    pub fn keep_alive(mut self, keep_alive: KeepAlive) -> Self {
        self.keep_alive = Some(keep_alive);
        self
    }

    /// Set think mode
    pub fn think(mut self, think: impl Into<ThinkType>) -> Self {
        self.think = Some(think.into());
        self
    }

    /// Set event callback for receiving intermediate content and events
    pub fn on_event(mut self, callback: impl Fn(ChatEvent) + Send + Sync + 'static) -> Self {
        self.event_callback = Some(Box::new(callback));
        self
    }

    /// Extract accumulated pre-tool content
    ///
    /// Returns the content generated before tool calls and clears the accumulator.
    /// This should be called after `chat()` returns to get any pre-tool content.
    pub fn take_pre_tool_content(&mut self) -> Option<PreToolContent> {
        if self.pre_tool_content.is_empty() {
            return None;
        }
        Some(PreToolContent {
            content: std::mem::take(&mut self.pre_tool_content),
            thinking: self.pre_tool_thinking.take(),
        })
    }

    /// Add an ephemeral message (not persisted to history)
    ///
    /// Ephemeral messages are prepended to requests but never saved.
    /// Used for continuation prompts after context compaction.
    pub fn push_ephemeral(&mut self, message: ChatMessage) {
        self.ephemeral_messages.push(message);
    }

    /// Emit an event if callback is set
    fn emit_event(&self, event: ChatEvent) {
        if let Some(ref callback) = self.event_callback {
            callback(event);
        }
    }

    /// Send a chat message and process tool calls with event emission
    pub async fn chat(
        &mut self,
        messages: Vec<ChatMessage>,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        if self.debug {
            for m in &messages {
                eprintln!("Hit {} with:", self.model);
                eprintln!("\t{:?}: '{}'", m.role, m.content);
            }
        }

        let request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Apply optional settings
        let request = self.apply_optional_settings(request);

        // Push initial messages to history
        for m in request.messages.clone() {
            self.history.push(m);
        }

        // Make the request
        let resp = self.ollama.send_chat_messages(self.build_request()).await?;

        // Process the response
        self.process_response(resp).await
    }

    /// Apply optional settings to request
    fn apply_optional_settings(&self, mut request: ChatMessageRequest) -> ChatMessageRequest {
        if let Some(ref keep_alive) = self.keep_alive {
            request = request.keep_alive(keep_alive.clone());
        }

        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        if let Some(ref format) = self.format {
            if self.tool_infos.is_empty() {
                request = request.format(format.clone());
            } else if let Some(last_message) = self.history.messages().last()
                && last_message.role == MessageRole::Tool
            {
                request = request.format(format.clone());
            }
        }

        request
    }

    /// Build a request from current history with ephemeral messages prepended
    fn build_request(&self) -> ChatMessageRequest {
        // Build messages: ephemeral first, then history
        let mut messages =
            Vec::with_capacity(self.ephemeral_messages.len() + self.history.messages().len());
        messages.extend(self.ephemeral_messages.iter().cloned());
        messages.extend(self.history.messages().iter().cloned());

        let mut request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Add tools - need to convert our CustomToolInfo to ollama-rs's ToolInfo
        // We serialize ours and it's compatible
        let tools_json = serde_json::to_string(&self.tool_infos).unwrap_or_default();
        let tools: Vec<ollama_rs::generation::tools::ToolInfo> =
            serde_json::from_str(&tools_json).unwrap_or_default();
        request = request.tools(tools);

        if let Some(ref keep_alive) = self.keep_alive {
            request = request.keep_alive(keep_alive.clone());
        }

        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        if let Some(ref format) = self.format {
            if self.tool_infos.is_empty() {
                request = request.format(format.clone());
            } else if let Some(last_message) = self.history.messages().last()
                && last_message.role == MessageRole::Tool
            {
                request = request.format(format.clone());
            }
        }

        request
    }

    /// Process response, handling tool calls with event emission
    async fn process_response(
        &mut self,
        resp: ChatMessageResponse,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check if there are tool calls
        if !resp.message.tool_calls.is_empty() {
            // Accumulate pre-tool content if present
            let has_content = !resp.message.content.trim().is_empty();
            let has_thinking = resp.message.thinking.is_some();

            if has_content || has_thinking {
                // Accumulate content
                if !resp.message.content.trim().is_empty() {
                    if !self.pre_tool_content.is_empty() {
                        self.pre_tool_content.push_str("\n\n");
                    }
                    self.pre_tool_content.push_str(&resp.message.content);
                }
                // Accumulate thinking (use the first one)
                if self.pre_tool_thinking.is_none() {
                    self.pre_tool_thinking = resp.message.thinking.clone();
                }

                // Emit event
                self.emit_event(ChatEvent::PreToolContent {
                    content: resp.message.content.clone(),
                    thinking: resp.message.thinking.clone(),
                });
            }

            // Push assistant message to history (with tool calls)
            self.history.push(resp.message.clone());

            // Execute each tool call
            let mut tools_executed = Vec::new();

            for call in resp.message.tool_calls.clone() {
                let tool_name = call.function.name.clone();
                let args = call.function.arguments.clone();

                // Emit tool call event
                self.emit_event(ChatEvent::ToolCall {
                    name: tool_name.clone(),
                    arguments: args.clone(),
                });

                if self.debug {
                    eprintln!("Tool call: {:?}", call.function);
                }

                let Some(tool) = self.tools.get_mut(&tool_name) else {
                    if self.debug {
                        eprintln!(
                            "\x1B[90m[DEBUG] Unknown tool '{}'. Available: {}\x1B[0m",
                            tool_name,
                            self.tools.keys().cloned().collect::<Vec<_>>().join(", ")
                        );
                    }
                    return Err(ollama_rs::error::OllamaError::ToolCallError(
                        ollama_rs::error::ToolCallError::UnknownToolName,
                    ));
                };

                let result = match tool.call(args.clone()).await {
                    Ok(result) => result,
                    Err(e) => {
                        if self.debug {
                            eprintln!(
                                "\x1B[90m[DEBUG] Tool '{}' call failed: {}\x1B[0m",
                                tool_name, e
                            );
                            eprintln!(
                                "\x1B[90m[DEBUG]   Arguments: {}\x1B[0m",
                                serde_json::to_string(&args).unwrap_or_else(|_| args.to_string())
                            );
                        }
                        return Err(ollama_rs::error::OllamaError::ToolCallError(
                            ollama_rs::error::ToolCallError::InternalToolError(e),
                        ));
                    }
                };

                if self.debug {
                    eprintln!("Tool response: {}", &result);
                }

                // Emit tool result event
                self.emit_event(ChatEvent::ToolResult {
                    name: tool_name.clone(),
                    result: result.clone(),
                });

                // Inter-tool context check: detect overflow and truncate if needed
                let check_result = self.check_and_handle_context_overflow(&tool_name, result);

                // Check if compaction is needed - stop and emit event
                if check_result.needs_compaction {
                    // Push the current result to history before stopping
                    self.history.push(ChatMessage::tool(check_result.result));
                    tools_executed.push(tool_name);

                    // Emit compaction needed event
                    self.emit_event(ChatEvent::ContextNeedsCompaction {
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                        tools_executed: tools_executed.clone(),
                    });

                    // Return error to signal compaction needed
                    let tools_str = tools_executed.join(", ");
                    return Err(ollama_rs::error::OllamaError::Other(format!(
                        "CONTEXT_NEEDS_COMPACT:{}:{}:{}",
                        check_result.tokens_used,
                        self.context_window.unwrap_or(0),
                        tools_str
                    )));
                }

                // Emit context events
                if check_result.was_truncated {
                    let result_tokens = estimate_tokens(&check_result.result);
                    self.emit_event(ChatEvent::ContextTruncated {
                        tool_name: tool_name.clone(),
                        original_tokens: check_result.tokens_used,
                        new_tokens: result_tokens,
                        context_window: self.context_window.unwrap_or(0),
                    });
                } else if check_result.is_near_limit {
                    self.emit_event(ChatEvent::ContextNearLimit {
                        tool_name: tool_name.clone(),
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                    });
                }

                // Push (possibly truncated) result to history
                self.history.push(ChatMessage::tool(check_result.result));
                tools_executed.push(tool_name);
            }

            // Recurse to get next response
            Box::pin(self.process_next()).await
        } else {
            // No tool calls - this is the final response
            // Push to history
            self.history.push(resp.message.clone());

            Ok(resp)
        }
    }

    /// Process next response after tool calls
    async fn process_next(&mut self) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check context overflow before sending to Ollama
        if let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) {
            let history_tokens = estimate_chat_messages_tokens(&self.history.messages());
            let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;
            let total_tokens = history_tokens + system_tokens;

            // Use EMERGENCY_BUFFER (3K remaining) to detect overflow
            let threshold = ctx_window.saturating_sub(EMERGENCY_BUFFER);

            if total_tokens > threshold {
                // Return error that will be caught by caller
                let msg = format!(
                    "Context overflow during tool execution: {} tokens used, {} available. Use /compact to reduce context.",
                    total_tokens, ctx_window
                );
                return Err(ollama_rs::error::OllamaError::Other(msg));
            }
        }

        let resp = self.ollama.send_chat_messages(self.build_request()).await?;

        self.process_response(resp).await
    }

    /// Get the number of registered tools (for future use)
    #[allow(dead_code)]
    pub fn tool_count(&self) -> usize {
        self.tools.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_continuation_tag_basic() {
        let content = r#"I've analyzed the first part. Let me continue.

<continuation_needed>
Reasoning paused: Analyzed file structure
Next step: Examine the main function
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Analyzed file structure");
        assert_eq!(tag.next_step, "Examine the main function");
        assert!(cleaned.contains("I've analyzed the first part"));
        assert!(!cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_multiline() {
        let content = r#"Some response here.

<continuation_needed>
Reasoning paused: Completed step 1
Next step: Process step 2
</continuation_need>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none(), "Should not parse without closing tag");
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_in_code_block() {
        let content = r#"Here's an example:

```
<continuation_needed>
Reasoning paused: In code block
Next step: Should not parse
</continuation_needed>
```

This should not be parsed as a continuation tag."#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(
            tag.is_none(),
            "Tags inside code blocks should not be parsed"
        );
        assert!(cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_empty_fields() {
        let content = r#"<continuation_needed>
Reasoning paused:
Next step:
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        // Empty fields should return None
        assert!(tag.is_none());
    }

    #[test]
    fn test_parse_continuation_tag_partial_fields() {
        let content = r#"<continuation_needed>
Reasoning paused: Half way through analysis
Next step:
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        // Should still parse if at least one field is filled
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Half way through analysis");
        assert!(tag.next_step.is_empty());
    }

    #[test]
    fn test_parse_continuation_tag_no_tag() {
        let content = "This is a normal response without any continuation tag.";

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none());
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_nested_tags() {
        // Nested tags shouldn't happen in practice, but if they do,
        // we parse from first open to first close and take the last matching values
        let content = r#"<continuation_needed>
Reasoning paused: First level
Next step: Second level
<continuation_needed>
Reasoning paused: Nested
Next step: Should ignore
</continuation_needed>
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        // We find the first </continuation_needed> (after "ignore")
        // and parse the content between, which includes all lines
        // The last matching field values win
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Nested"); // Last "Reasoning paused:" wins
        assert_eq!(tag.next_step, "Should ignore"); // Last "Next step:" wins
    }
}
