//! Custom Coordinator with callbacks for intermediate content
//!
//! This is our own implementation that provides:
//! - Pre-tool content callbacks (content before tool calls)
//! - Thinking content callbacks
//! - Full control over tool execution flow
//! - Inter-tool context overflow detection

/// Error string returned when the user cancels tool execution (Ctrl+C).
/// Checked by the caller (`handle_user_message_stream`) to suppress error display.
pub const CANCELLED_BY_USER: &str = "CANCELLED_BY_USER";

use std::{collections::HashMap, future::Future, pin::Pin};

use ollama_rs::re_exports::serde::{Deserialize, Serialize, de::DeserializeOwned};
use ollama_rs::{
    generation::{
        chat::{ChatMessage, ChatMessageResponse, request::ChatMessageRequest},
        parameters::ThinkType,
    },
    history::ChatHistory,
    models::ModelOptions,
    re_exports::schemars::{JsonSchema, Schema, generate::SchemaSettings},
};
use serde_json::Value;

use crate::chat::llm_event::LlmEvent;
use crate::context_overflow::{
    calculate_available_budget, calculate_thresholds, is_emergency_context,
    needs_inter_tool_compaction,
};
use crate::tokens::{ContextUsage, MESSAGE_OVERHEAD, estimate_tokens};
use crate::utils::truncate_to_budget;

/// Result type for tool execution
pub type ToolResult = std::result::Result<String, Box<dyn std::error::Error + Send + Sync>>;

/// Trait to hold and call tools - our own implementation since ollama-rs's ToolHolder is private
/// W2 #121: bound relaxed from `Send + Sync` to `Send` because
/// tool futures await `LlmProvider::embed`/`chat` which are Send only.
pub trait ToolHolder: Send {
    fn call(&mut self, parameters: Value) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send>>;
}

impl<T: crate::tools::Tool> ToolHolder for T {
    fn call(&mut self, parameters: Value) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send>> {
        Box::pin(async move {
            // Handle different JSON formats that models might return
            let param_value =
                match serde_json::from_value::<ToolCallFunctionParser>(parameters.clone()) {
                    Ok(func) => func.arguments,
                    Err(_) => parameters,
                };

            let params: T::Params = serde_json::from_value(param_value)?;
            T::call(self, params).await
        })
    }
}

/// Helper struct for parsing tool call function JSON
#[derive(Deserialize)]
struct ToolCallFunctionParser {
    #[expect(dead_code)]
    name: String,
    arguments: Value,
}

/// Tool type enum
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CustomToolType {
    #[serde(rename_all(deserialize = "PascalCase"))]
    Function,
}

/// Tool function info
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolFunctionInfo {
    pub name: String,
    pub description: String,
    pub parameters: Schema,
}

/// Our own ToolInfo since ollama-rs's ToolInfo::new is private
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolInfo {
    #[serde(rename = "type")]
    pub tool_type: CustomToolType,
    pub function: CustomToolFunctionInfo,
}

impl CustomToolInfo {
    /// Create a new ToolInfo for a given Tool type
    ///
    /// The bound is `crate::tools::Tool` (our own trait). Tools generated
    /// by `#[sprachspiel::tool]` implement this trait directly (and also
    /// `ollama_rs::Tool` via the dual-impl macro for ollama-rs
    /// compatibility). There is no blanket impl — tools must implement
    /// `crate::tools::Tool` directly to be registered here.
    pub fn new<P: DeserializeOwned + JsonSchema, T: crate::tools::Tool<Params = P>>() -> Self {
        let mut settings = SchemaSettings::draft07();
        settings.inline_subschemas = true;
        let generator = settings.into_generator();

        let parameters = generator.into_root_schema_for::<P>();

        Self {
            tool_type: CustomToolType::Function,
            function: CustomToolFunctionInfo {
                name: T::name().to_string(),
                description: T::description().to_string(),
                parameters,
            },
        }
    }
}

/// Pre-tool content accumulated during processing
///
/// Contains text generated by the assistant before tool calls,
/// which should be saved separately from the final response.
#[derive(Debug, Clone, Default)]
pub struct PreToolContent {
    /// Content generated before tool calls
    pub content: String,
    /// Thinking content (if any)
    pub thinking: Option<String>,
}

/// Continuation tag parsed from LLM response
///
/// When the LLM detects context is nearly full and needs to pause,
/// it emits this tag with checkpoint information for resumption.
#[derive(Debug, Clone)]
pub struct ContinuationTag {
    /// Where reasoning was paused
    pub paused_at: String,
    /// What the LLM was about to do next
    pub next_step: String,
}

/// Parse continuation tag from LLM response
///
/// Extracts the <continuation_needed> tag content and returns
/// both the cleaned response (without the tag) and the parsed tag.
///
/// Returns (cleaned_content, Some(tag)) if tag found and parsed,
/// or (original_content, None) if no tag or invalid.
pub fn parse_continuation_tag(content: &str) -> (String, Option<ContinuationTag>) {
    // Find the tag
    let start_tag = "<continuation_needed>";
    let end_tag = "</continuation_needed>";

    let start_pos = match content.find(start_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Check if tag is inside a code block (should NOT be parsed)
    let before_tag = &content[..start_pos];
    let code_block_count = before_tag.matches("```").count();
    if code_block_count % 2 == 1 {
        // Inside a code block, don't parse
        return (content.to_string(), None);
    }

    let end_pos = match content.find(end_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Extract tag content
    let tag_content = &content[start_pos + start_tag.len()..end_pos];

    // Parse fields
    let mut paused_at = String::new();
    let mut next_step = String::new();

    for line in tag_content.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("Reasoning paused:") {
            paused_at = value.trim().to_string();
        } else if let Some(value) = line.strip_prefix("Next step:") {
            next_step = value.trim().to_string();
        }
    }

    // Create cleaned content by removing the tag
    let cleaned = format!(
        "{}{}",
        &content[..start_pos],
        &content[end_pos + end_tag.len()..]
    );

    // Normalize whitespace in cleaned content
    let cleaned = cleaned.trim().to_string();

    // Require at least one field to be filled
    if paused_at.is_empty() && next_step.is_empty() {
        return (content.to_string(), None);
    }

    (
        cleaned,
        Some(ContinuationTag {
            paused_at,
            next_step,
        }),
    )
}

/// Event emitted during chat processing
#[derive(Debug, Clone)]
pub enum ChatEvent {
    /// Content generated before tool calls (often thinking/intro text).
    PreToolContent {
        content: String,
        thinking: Option<String>,
    },
    /// Context is near limit after tool execution (inter-tool threshold)
    /// Indicates compaction may be needed before next tool
    ContextNearLimit {
        tool_name: String,
        tokens_used: usize,
        context_window: usize,
    },
    /// Context was truncated during tool execution (emergency threshold)
    /// Indicates last tool result was truncated to fit
    ContextTruncated {
        tool_name: String,
        original_tokens: usize,
        new_tokens: usize,
        context_window: usize,
    },
    /// Context needs compaction during tool execution (compaction threshold)
    /// Signals that tool execution should pause for compaction
    ContextNeedsCompaction {
        tokens_used: usize,
        context_window: usize,
        tools_executed: Vec<String>,
    },
    /// Tool execution lifecycle events (W2 #122 skeleton).
    ///
    /// Emitted when a tool starts and finishes execution. Full
    /// partial-output streaming is deferred to a follow-up PR.
    ToolExecutionStarted {
        /// Tool-call id this execution belongs to.
        tool_call_id: String,
        /// Tool name.
        name: String,
        /// Final parsed arguments.
        args: serde_json::Value,
    },
    ToolExecutionFinished {
        /// Tool-call id this execution belongs to.
        tool_call_id: String,
        /// Tool result string (or error message).
        result: String,
        /// Whether the tool returned an error.
        is_error: bool,
    },
}

/// Result of checking context overflow after tool execution
struct ContextCheckResult {
    /// The result to use (possibly truncated)
    result: String,
    /// Whether context is near limit (inter-tool threshold)
    is_near_limit: bool,
    /// Whether result was truncated (emergency threshold)
    was_truncated: bool,
    /// Tokens used (for events)
    tokens_used: usize,
    /// Whether compaction is needed before continuing
    needs_compaction: bool,
}

/// A coordinator for managing chat interactions with event callbacks.
pub struct CustomCoordinator<C: ChatHistory> {
    model: String,
    ollama: crate::provider::Ollama,
    options: ModelOptions,
    history: C,
    tool_infos: Vec<CustomToolInfo>,
    tools: HashMap<String, Box<dyn ToolHolder>>,
    think: Option<ThinkType>,
    /// Callback for events
    event_callback: Option<Box<dyn Fn(ChatEvent) + Send + Sync>>,
    /// Streaming token callback (stored for multi-round ReAct loops).
    token_callback: Option<Box<dyn Fn(String) + Send + Sync>>,
    /// Streaming thinking callback (stored for multi-round ReAct loops).
    thinking_callback: Option<Box<dyn Fn(String) + Send + Sync>>,
    /// Tool-call detected callback (stored for multi-round ReAct loops).
    tool_call_callback: Option<Box<dyn Fn() + Send + Sync>>,
    /// Tool-call preview callback (stored for multi-round ReAct loops).
    #[allow(clippy::type_complexity)] // signature mirrors `on_tool_call_preview` callback
    tool_preview_callback: Option<Box<dyn Fn(String, String, serde_json::Value) + Send + Sync>>,
    /// Provider retry/event callback (stored for multi-round ReAct loops).
    provider_event_callback: Option<Box<dyn Fn(LlmEvent) + Send + Sync>>,
    /// Context window size for overflow detection during tool execution
    context_window: Option<usize>,
    /// System prompt for token estimation
    system_prompt: Option<String>,
    /// Real token count from Ollama's prompt_eval_count (if available)
    /// This is the ACTUAL token count, not an estimation.
    /// Should always be used when available for accurate overflow detection.
    real_history_tokens: Option<usize>,
    /// Number of messages in history at the start of this request.
    /// Used to distinguish between session history (base) and new messages (growth).
    initial_message_count: usize,
    /// Accumulated pre-tool content (text generated before tool calls)
    pre_tool_content: String,
    pre_tool_thinking: Option<String>,
    /// Ephemeral messages (not persisted to history)
    /// Used for continuation prompts after context compaction
    ephemeral_messages: Vec<ChatMessage>,
    /// Cancellation token for aborting tool execution mid-loop.
    /// When cancelled, the tool loop stops after the current tool finishes
    /// and returns an error that the caller interprets as user cancellation.
    cancel_token: Option<tokio_util::sync::CancellationToken>,
    /// Monotonic counter for generating unique tool_call_ids.
    tool_call_counter: u64,
    /// Counter for retries inside the ReAct loop (process_next_stream).
    /// Covers two cases: "invalid tool call arguments" (provider rejects
    /// malformed tool call JSON) and "SSE stream idle timeout" (provider
    /// accepts connection but doesn't emit chunks within the idle timeout).
    /// Prevents infinite loops when the provider persistently fails.
    react_retry_count: u32,
    /// Stream ids emitted by the provider, kept in the same order as
    /// `tool_calls` so the ReAct execution loop can reuse them instead of
    /// synthesizing divergent ids. Keeps preview and execution ids in sync
    /// for `freeze_tool_preview_by_name`. Reset at the start of each `stream_turn`.
    stream_tool_call_ids: Vec<String>,
}

impl<C: ChatHistory> CustomCoordinator<C> {
    /// Creates a new `CustomCoordinator` instance.
    pub fn new(ollama: crate::provider::Ollama, model: String, history: C) -> Self {
        Self {
            model,
            ollama,
            options: ModelOptions::default(),
            history,
            tool_infos: Vec::default(),
            tools: HashMap::default(),
            think: None,
            event_callback: None,
            token_callback: None,
            thinking_callback: None,
            tool_call_callback: None,
            tool_preview_callback: None,
            provider_event_callback: None,
            context_window: None,
            system_prompt: None,
            real_history_tokens: None,
            initial_message_count: 0,
            pre_tool_content: String::new(),
            pre_tool_thinking: None,
            ephemeral_messages: Vec::new(),
            cancel_token: None,
            tool_call_counter: 0,
            react_retry_count: 0,
            stream_tool_call_ids: Vec::new(),
        }
    }

    /// Store streaming callbacks so they can be reused across ReAct rounds.
    ///
    /// W2 #122: `process_response` executes tools and then needs to continue
    /// streaming the next assistant turn. The callbacks are owned by the
    /// original caller (`core.rs`), so we box them here rather than threading
    /// them through every recursive call.
    fn set_streaming_callbacks(
        &mut self,
        on_token: impl Fn(String) + Send + Sync + 'static,
        on_thinking: impl Fn(String) + Send + Sync + 'static,
        on_tool_call: impl Fn() + Send + Sync + 'static,
        on_tool_call_preview: impl Fn(String, String, serde_json::Value) + Send + Sync + 'static,
        on_provider_event: impl Fn(LlmEvent) + Send + Sync + 'static,
    ) {
        self.token_callback = Some(Box::new(on_token));
        self.thinking_callback = Some(Box::new(on_thinking));
        self.tool_call_callback = Some(Box::new(on_tool_call));
        self.tool_preview_callback = Some(Box::new(on_tool_call_preview));
        self.provider_event_callback = Some(Box::new(on_provider_event));
    }

    /// Check context overflow and handle truncation if needed
    ///
    /// Returns a ContextCheckResult with the (possibly truncated) result and status flags.
    fn check_and_handle_context_overflow(&self, result: String) -> ContextCheckResult {
        let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) else {
            log::debug!("check_and_handle_context_overflow: no context_window or system_prompt");
            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: 0,
                needs_compaction: false,
            };
        };

        // Calculate total tokens:
        // 1. real_history_tokens: Base from session (Ollama's prompt_eval_count) - EXACT
        // 2. growth_tokens: New messages during this request (assistant + tool results) - ESTIMATED
        // 3. system_tokens: System prompt
        // 4. tool_tokens: Tool definitions
        // 5. result_tokens: Current tool result being processed

        // W2 #121 follow-up: use ContextUsage as the single source of truth.
        // Build a ContextUsage from the API-reported prompt_tokens (or 0 if
        // we don't have one yet) and then `with_growth` for the new messages
        // added in this request. The final `total_tokens` is what was
        // previously called `total_after_add` — same value, just produced
        // by the unified path.
        let all_messages = self.history.messages().len();
        let growth_messages = &self.history.messages()[self.initial_message_count..];
        // Pre-growth total: the API-reported prompt size if available,
        // else 0 (fresh session with no messages to summarize).
        let pre_growth_base = self.real_history_tokens.unwrap_or(0);
        let base_usage = match self.real_history_tokens {
            Some(tokens) => ContextUsage::from_api_usage(tokens as u32, prompt, 0),
            None => {
                log::debug!("[check_and_handle] No real_history_tokens; using local estimate");
                ContextUsage {
                    system_tokens: 0, // diagnostic only — `total` is what matters
                    tools_tokens: 0,
                    history_tokens: pre_growth_base,
                    total_tokens: pre_growth_base,
                    source: crate::tokens::ContextSource::Estimated,
                }
            }
        };
        let usage = base_usage
            .with_growth(growth_messages)
            .with_tool_result(&result);
        let total_after_add = usage.total_tokens;
        // W2 #121 follow-up: keep `base_tokens` available for legacy log
        // lines and threshold math. It's the pre-growth total — `base_usage.total_tokens`.
        let base_tokens = base_usage.total_tokens;
        // growth_tokens / result_tokens are kept only for the diagnostic
        // log lines below (which print them separately).
        let growth_tokens = usage
            .history_tokens
            .saturating_sub(base_usage.history_tokens);
        let _result_tokens = usage.total_tokens - base_usage.total_tokens - growth_tokens;

        // Tool definitions (each tool: name + description + parameters + overhead)
        // NOTE: These are already included in base_tokens from Ollama's prompt_eval_count
        // We calculate them separately only for diagnostic purposes
        let tool_tokens: usize = self
            .tool_infos
            .iter()
            .map(|info| {
                let name_tokens = estimate_tokens(&info.function.name);
                let desc_tokens = estimate_tokens(&info.function.description);
                let params_tokens = estimate_tokens(
                    &serde_json::to_string(&info.function.parameters).unwrap_or_else(|e| {
                        // Every eprintln! in production code MUST have a
                        // corresponding log::warn! (AGENTS.md steering rule).
                        // Here the equivalent is `unwrap_or_default` for
                        // serializing tool parameters for token estimation;
                        // log the failure so it's not silent.
                        log::warn!("Failed to serialize tool parameters for token estimation: {e}");
                        String::new()
                    }),
                );
                name_tokens + desc_tokens + params_tokens + MESSAGE_OVERHEAD
            })
            .sum();

        // System prompt tokens - also included in base_tokens from Ollama
        let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;

        // Result tokens - the current tool result being processed
        let result_tokens = estimate_tokens(&result);

        // W2 #121 follow-up: `total_after_add` is now derived from the
        // `ContextUsage` we built above. Same value as
        //   base_tokens + growth_tokens + result_tokens
        // but produced by the unified `with_growth` / `with_tool_result`
        // path. The legacy `growth_tokens` / `result_tokens` locals are
        // kept only for the debug log lines below (which print them
        // separately for diagnostic purposes).
        let _ = result_tokens; // see usage.total_tokens below; kept for log compat

        // Format token values: show as raw number if < 1000, otherwise as NK
        fn fmt_tokens(v: usize) -> String {
            if v >= 1000 {
                format!("{}K", v / 1000)
            } else {
                format!("{}", v)
            }
        }

        let (_, compaction_buffer, _, _) = calculate_thresholds(ctx_window);

        // Debug log (only when debug enabled)
        log::debug!("[INTER-TOOL-CHECK-DETAILS]");
        log::debug!(
            "  base_tokens={} (from the LLM server, includes sys+tools+history)",
            base_tokens
        );
        log::debug!("  initial_message_count={}", self.initial_message_count);
        log::debug!("  all_messages={}", all_messages);
        log::debug!(
            "  growth_messages={} (new this request)",
            growth_messages.len()
        );
        log::debug!("  growth_tokens={} (estimated)", growth_tokens);
        log::debug!(
            "  tool_tokens={} (diagnostic, already in base)",
            tool_tokens
        );
        log::debug!(
            "  system_tokens={} (diagnostic, already in base)",
            system_tokens
        );
        log::debug!("  result_tokens={} (current tool result)", result_tokens);
        log::debug!(
            "[INTER-TOOL-CHECK] total={}/{} remaining={} buffer={}",
            fmt_tokens(total_after_add),
            fmt_tokens(ctx_window),
            fmt_tokens(ctx_window.saturating_sub(total_after_add)),
            fmt_tokens(compaction_buffer)
        );

        if is_emergency_context(total_after_add, ctx_window) {
            let available = calculate_available_budget(base_tokens + growth_tokens, ctx_window);
            let original_tokens = estimate_tokens(&result);
            let truncated = truncate_to_budget(&result, available);
            let truncated_tokens = estimate_tokens(&truncated);
            let reduction = original_tokens.saturating_sub(truncated_tokens);

            // Only show truncation warning if significant reduction
            if reduction > 100 || (original_tokens > 1000 && reduction * 100 / original_tokens > 10)
            {
                log::warn!(
                    "[EMERGENCY] Context at {}% ({} tokens). Truncated tool result: {} → {} tokens",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add,
                    original_tokens,
                    truncated_tokens
                );
            }

            return ContextCheckResult {
                result: truncated,
                is_near_limit: true,
                was_truncated: reduction > 0,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        // W2 #121: Defensive pre-truncation for tool results.
        //
        // `estimate_tokens` (in src/tokens.rs) uses a word-based heuristic
        // (~0.75 words/token, GPT-style) which UNDERCOUNTS by 30-50% vs
        // real model tokenizers (Llama, Mistral, Qwen) for mixed content
        // (code, JSON, non-English text, tool results). Empirically: we
        // estimated 27K tokens for a request the model counted as 40K.
        //
        // By the time `is_emergency_context` triggers (95% of ctx_window)
        // we are ALREADY overflowing the real tokenizer's count.
        // Preemptively truncate at 75% of the ESTIMATE so there's headroom
        // for the real tokenizer to be ~33% higher and still fit.
        //
        // TODO(W2 #121 follow-up): A real tokenizer would give 100%
        // accuracy and let us size to the actual budget. Two options:
        //   1. tiktoken-rs (GPT-style BPE) — ~5MB binary, ~100ms load.
        //      Doesn't match Llama/Mistral/Qwen tokenizers 100%.
        //   2. Ollama's /api/tokenize endpoint — model-specific, no
        //      binary bloat, but adds HTTP RTT on the compaction path.
        // Deferred until we have a clearer accuracy-vs-complexity trade-off
        // from real-world data.
        if total_after_add >= ctx_window.saturating_mul(3) / 4 {
            let target = ctx_window.saturating_mul(70) / 100; // 70% of ctx_window
            let excess = total_after_add.saturating_sub(target);
            let available = estimate_tokens(&result).saturating_sub(excess);
            let original_tokens = estimate_tokens(&result);
            let truncated = truncate_to_budget(&result, available);
            let truncated_tokens = estimate_tokens(&truncated);
            let reduction = original_tokens.saturating_sub(truncated_tokens);

            if reduction > 100 || (original_tokens > 1000 && reduction * 100 / original_tokens > 10)
            {
                log::warn!(
                    "[PREEMPTIVE] Estimated context at {}% ({} tokens), \
                     truncated tool result to leave headroom for real tokenizer: \
                     {} → {} tokens",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add,
                    original_tokens,
                    truncated_tokens,
                );
            }

            return ContextCheckResult {
                result: truncated,
                is_near_limit: true,
                was_truncated: reduction > 0,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        let remaining = ctx_window.saturating_sub(total_after_add);
        if remaining < compaction_buffer {
            // Only trigger compaction if there's history to compact
            // base_tokens == 0 means fresh session with no messages to summarize
            if base_tokens == 0 {
                // Fresh session - nothing to compact, just proceed
                // Context will grow as conversation proceeds, future requests will have base > 0
                log::debug!(
                    "[INTER-TOOL] Fresh session (base=0), nothing to compact. Proceeding... ({}K/{}K)",
                    total_after_add / 1000,
                    ctx_window / 1000
                );
                return ContextCheckResult {
                    result,
                    is_near_limit: true,
                    was_truncated: false,
                    tokens_used: total_after_add,
                    needs_compaction: false,
                };
            }

            log::warn!(
                "⏳ [INTER-TOOL] Context: {}K/{}K ({}% used, {}K remaining). Buffer: {}K. NEEDS COMPACTION.",
                total_after_add / 1000,
                ctx_window / 1000,
                (total_after_add * 100) / ctx_window,
                remaining / 1000,
                compaction_buffer / 1000
            );

            return ContextCheckResult {
                result,
                is_near_limit: true,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: true,
            };
        }

        if needs_inter_tool_compaction(total_after_add, ctx_window) {
            log::debug!(
                "[INFO] Context at {}% ({} tokens). Inter-tool warning.",
                (total_after_add) * 100 / ctx_window,
                total_after_add
            );

            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        ContextCheckResult {
            result,
            is_near_limit: false,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: false,
        }
    }

    /// Set the context window size for overflow detection
    pub fn context_window(mut self, context_window: usize) -> Self {
        self.context_window = Some(context_window);
        self
    }

    /// Set the system prompt for token estimation
    pub fn system_prompt(mut self, system_prompt: String) -> Self {
        self.system_prompt = Some(system_prompt);
        self
    }

    /// Set the real history token count from Ollama's prompt_eval_count.
    /// This should ALWAYS be used when available for accurate overflow detection.
    /// Estimation is a fallback when real tokens are not available.
    pub fn real_history_tokens(mut self, tokens: usize) -> Self {
        self.real_history_tokens = Some(tokens);
        self
    }

    /// Add a tool to the coordinator
    ///
    /// The bound is `crate::tools::Tool` (our own trait, generated by
    /// `#[sprachspiel::tool]`). There is no blanket impl — tools that
    /// only implement `ollama_rs::Tool` cannot be registered here. (In
    /// practice, all tools in the codebase are migrated to the new
    /// macro and satisfy this bound directly.)
    pub fn add_tool<T: crate::tools::Tool + 'static>(mut self, tool: T) -> Self {
        self.tool_infos.push(CustomToolInfo::new::<T::Params, T>());
        self.tools.insert(T::name().to_string(), Box::new(tool));
        self
    }

    /// Set model options
    pub fn options(mut self, options: ModelOptions) -> Self {
        self.options = options;
        self
    }

    /// Set think mode
    pub fn think(mut self, think: impl Into<ThinkType>) -> Self {
        self.think = Some(think.into());
        self
    }

    /// Set event callback for receiving intermediate content and events
    pub fn on_event(mut self, callback: impl Fn(ChatEvent) + Send + Sync + 'static) -> Self {
        self.event_callback = Some(Box::new(callback));
        self
    }

    /// Extract accumulated pre-tool content
    ///
    /// Returns the content generated before tool calls and clears the accumulator.
    /// This should be called after `chat()` returns to get any pre-tool content.
    pub fn take_pre_tool_content(&mut self) -> Option<PreToolContent> {
        if self.pre_tool_content.is_empty() {
            return None;
        }
        Some(PreToolContent {
            content: std::mem::take(&mut self.pre_tool_content),
            thinking: self.pre_tool_thinking.take(),
        })
    }

    /// Add an ephemeral message (not persisted to history)
    ///
    /// Ephemeral messages are prepended to requests but never saved.
    /// Used for continuation prompts after context compaction.
    pub fn push_ephemeral(&mut self, message: ChatMessage) {
        self.ephemeral_messages.push(message);
    }

    /// Set the cancellation token for tool loop interruption.
    ///
    /// When the token is cancelled, the tool execution loop stops after
    /// the current tool finishes and returns an error. The caller
    /// (event loop) interprets this as user-initiated cancellation.
    pub fn cancel_token(mut self, token: tokio_util::sync::CancellationToken) -> Self {
        self.cancel_token = Some(token);
        self
    }

    /// Emit an event if callback is set
    fn emit_event(&self, event: ChatEvent) {
        if let Some(ref callback) = self.event_callback {
            callback(event);
        }
    }

    /// Send a chat message and process tool calls with event emission
    pub async fn chat(
        &mut self,
        messages: Vec<ChatMessage>,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        for m in &messages {
            log::debug!("Hit {} with:", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        let request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Apply optional settings
        let request = self.apply_optional_settings(request);

        // Push initial messages to history
        for m in request.messages.clone() {
            self.history.push(m);
        }

        // Store how many messages we started with (to distinguish base from growth)
        self.initial_message_count = self.history.messages().len();

        // Make the request
        let resp = self.ollama.send_chat_messages(self.build_request()).await?;

        // Process the response (non-streaming path — content was not streamed)
        self.process_response(resp, /*already_streamed=*/ false)
            .await
    }

    /// Send a chat message with streaming and process tool calls.
    ///
    /// This is the streaming equivalent of `chat()`. Instead of waiting for
    /// the full response, it streams token chunks through the provided
    /// `on_token` callback. When the stream completes:
    /// - If no tool calls: returns the accumulated response
    /// - If tool calls: enters the non-streaming tool loop (since tool
    ///   execution must complete before the next request)
    ///
    /// The `on_token` callback is called with each content token chunk.
    /// The `on_thinking` callback is called with each thinking chunk.
    /// Both callbacks must be `Send + Sync` for use in async tasks.
    ///
    /// If `cancel_token` is provided and becomes cancelled during streaming,
    /// the stream is aborted and the accumulated partial content is returned
    /// as the response.
    #[expect(clippy::too_many_arguments)] // callback set is intentionally explicit
    pub async fn chat_stream(
        &mut self,
        messages: Vec<ChatMessage>,
        on_token: impl Fn(String) + Send + Sync + 'static,
        on_thinking: impl Fn(String) + Send + Sync + 'static,
        on_tool_call: impl Fn() + Send + Sync + 'static,
        on_tool_call_preview: impl Fn(String, String, serde_json::Value) + Send + Sync + 'static,
        on_provider_event: impl Fn(LlmEvent) + Send + Sync + 'static,
        cancel_token: Option<tokio_util::sync::CancellationToken>,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        for m in &messages {
            log::debug!("Hit {} with (stream):", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        let request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Apply optional settings
        let request = self.apply_optional_settings(request);

        // Push initial messages to history
        for m in request.messages.clone() {
            self.history.push(m);
        }

        // Store how many messages we started with
        self.initial_message_count = self.history.messages().len();

        // Store callbacks for reuse in later ReAct rounds.
        self.set_streaming_callbacks(
            on_token,
            on_thinking,
            on_tool_call,
            on_tool_call_preview,
            on_provider_event,
        );
        self.cancel_token = cancel_token;

        // Start the streaming request
        let request = self.build_request();
        let response = self.stream_turn(request).await?;

        // ReAct loop: while the assistant keeps emitting tool calls, execute
        // them and stream the next turn.
        let mut current_response = response;
        loop {
            if current_response.message.tool_calls.is_empty() {
                return Ok(current_response);
            }
            current_response = self.process_response(current_response, true).await?;
        }
    }

    /// Internal streaming turn handler. Consumes a raw `LlmStreamEvent` stream
    /// and returns a legacy `ChatMessageResponse` for the rest of the
    /// coordinator to process.
    async fn stream_turn(
        &mut self,
        request: ChatMessageRequest,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        let mut stream = self
            .ollama
            .send_chat_messages_stream_events(request)
            .await
            .map_err(crate::provider::ollama_shim::convert_provider_error)?;

        let mut full_content = String::new();
        let mut full_thinking: Option<String> = None;
        // Bug A fix: capture usage from LlmStreamEvent::Done so the final
        // ChatMessageResponse carries real prompt_eval_count / eval_count.
        // Previously this was always None, causing TokenMetrics::default()
        // (all zeros) and a misleadingly low status bar token count.
        let mut final_data: Option<ollama_rs::generation::chat::ChatMessageFinalResponseData> =
            None;
        let mut tool_calls: Vec<ollama_rs::generation::tools::ToolCall> = Vec::new();
        let mut tool_call_previews: std::collections::HashMap<
            u32,
            (String, String, serde_json::Value),
        > = std::collections::HashMap::new();
        // Emit `ToolCallStarted` exactly once per turn so the event loop
        // transitions to `ToolCall` state and freezes previews at the right
        // time.
        let mut tool_call_started_emitted = false;
        // Reset the stream id buffer so it lines up with `tool_calls` for the
        // upcoming ReAct execution loop.
        self.stream_tool_call_ids.clear();
        let model = self.model.clone();
        let created_at = String::new();

        use futures::StreamExt;

        while let Some(event_result) = stream.next().await {
            if let Some(ref ct) = self.cancel_token
                && ct.is_cancelled()
            {
                log::debug!("Stream cancelled by user");
                break;
            }

            match event_result {
                Ok(event) => match event {
                    crate::provider::types::LlmStreamEvent::TextDelta { delta } => {
                        if let Some(ref cb) = self.token_callback {
                            cb(delta.clone());
                        }
                        full_content.push_str(&delta);
                    }
                    crate::provider::types::LlmStreamEvent::ThinkingDelta { delta } => {
                        if let Some(ref cb) = self.thinking_callback {
                            cb(delta.clone());
                        }
                        full_thinking
                            .get_or_insert_with(String::new)
                            .push_str(&delta);
                    }
                    crate::provider::types::LlmStreamEvent::ToolCallStart { index, id, name } => {
                        // Emit `ToolCallStarted` once per turn so the event
                        // loop transitions to `ToolCall` state immediately.
                        if !tool_call_started_emitted {
                            tool_call_started_emitted = true;
                            if let Some(ref cb) = self.tool_call_callback {
                                cb();
                            }
                        }
                        let id = id.unwrap_or_default();
                        let name = name.unwrap_or_default();
                        tool_call_previews.insert(
                            index,
                            (
                                id.clone(),
                                name.clone(),
                                serde_json::Value::Object(serde_json::Map::new()),
                            ),
                        );
                        if let Some(ref cb) = self.tool_preview_callback {
                            cb(id, name, serde_json::Value::Object(serde_json::Map::new()));
                        }
                    }
                    crate::provider::types::LlmStreamEvent::ToolCallDelta {
                        index,
                        id,
                        name_delta,
                        argument_delta,
                    } => {
                        if let Some((existing_id, existing_name, existing_args)) =
                            tool_call_previews.get_mut(&index)
                        {
                            if let Some(id) = id {
                                *existing_id = id;
                            }
                            if let Some(name) = name_delta {
                                *existing_name = name;
                            }
                            // Accumulate argument_delta from the start:
                            // the initial args from ToolCallStart are an
                            // empty object, while the first delta is partial
                            // JSON that must be concatenated before parsing.
                            let raw = match existing_args {
                                serde_json::Value::String(s) => {
                                    let mut s = s.clone();
                                    s.push_str(&argument_delta);
                                    s
                                }
                                serde_json::Value::Object(o) if o.is_empty() => {
                                    argument_delta.clone()
                                }
                                _ => argument_delta.clone(),
                            };
                            let parsed = serde_json::from_str(&raw).unwrap_or_else(|_| {
                                if raw.is_empty() {
                                    serde_json::Value::Object(serde_json::Map::new())
                                } else {
                                    serde_json::Value::String(raw.clone())
                                }
                            });
                            *existing_args = parsed.clone();
                            if let Some(ref cb) = self.tool_preview_callback {
                                cb(existing_id.clone(), existing_name.clone(), parsed);
                            }
                        }
                    }
                    crate::provider::types::LlmStreamEvent::ToolCallEnd { call, .. } => {
                        // Preserve the stream's tool_call id for the ReAct
                        // execution loop, since `ollama_rs::ToolCall` has no
                        // id field. We carry it in a parallel vec.
                        self.stream_tool_call_ids.push(call.id.clone());
                        // Update the preview with the final parsed arguments.
                        // During streaming, deltas are partial JSON fragments;
                        // ToolCallEnd carries the complete, parsed object.
                        let preview_index = tool_calls.len() as u32;
                        if let Some((existing_id, existing_name, existing_args)) =
                            tool_call_previews.get_mut(&preview_index)
                        {
                            if !call.id.is_empty() {
                                *existing_id = call.id.clone();
                            }
                            if existing_name.is_empty() && !call.name.is_empty() {
                                *existing_name = call.name.clone();
                            }
                            *existing_args = call.arguments.clone();
                            if let Some(ref cb) = self.tool_preview_callback {
                                cb(
                                    existing_id.clone(),
                                    existing_name.clone(),
                                    call.arguments.clone(),
                                );
                            }
                        }
                        tool_calls.push(ollama_rs::generation::tools::ToolCall {
                            function: ollama_rs::generation::tools::ToolCallFunction {
                                name: call.name,
                                arguments: call.arguments,
                            },
                        });
                    }
                    crate::provider::types::LlmStreamEvent::Done { reason: _, usage } => {
                        // Bug A fix: capture usage so final_data is populated.
                        if let Some(u) = usage
                            && (u.prompt_tokens > 0 || u.completion_tokens > 0)
                        {
                            final_data =
                                Some(ollama_rs::generation::chat::ChatMessageFinalResponseData {
                                    total_duration: 0,
                                    load_duration: 0,
                                    prompt_eval_count: u.prompt_tokens as u64,
                                    prompt_eval_duration: 0,
                                    eval_count: u.completion_tokens as u64,
                                    eval_duration: 0,
                                });
                            // TurnMetrics: emit intermediate status bar update so
                            // the context count reflects each ReAct round, not
                            // just the final Complete.
                            if let Some(ref cb) = self.provider_event_callback {
                                cb(LlmEvent::TurnMetrics {
                                    prompt_tokens: u.prompt_tokens,
                                    completion_tokens: u.completion_tokens,
                                });
                            }
                        }
                    }
                    crate::provider::types::LlmStreamEvent::ProviderRetryStarted {
                        attempt,
                        max_attempts,
                        delay_ms,
                        reason,
                    } => {
                        if let Some(ref cb) = self.provider_event_callback {
                            cb(LlmEvent::ProviderRetryStarted {
                                attempt,
                                max_attempts,
                                delay_ms,
                                reason,
                            });
                        }
                    }
                    crate::provider::types::LlmStreamEvent::ProviderRetryFinished {
                        success,
                        attempt,
                    } => {
                        if let Some(ref cb) = self.provider_event_callback {
                            cb(LlmEvent::ProviderRetryFinished { success, attempt });
                        }
                    }
                    _ => {}
                },
                Err(err) => {
                    log::error!("Stream error in custom_coordinator: {err}");
                    return Err(crate::provider::ollama_shim::convert_provider_error(err));
                }
            }
        }

        let msg = ollama_rs::generation::chat::ChatMessage {
            role: ollama_rs::generation::chat::MessageRole::Assistant,
            content: full_content,
            tool_calls: tool_calls.clone(),
            images: None,
            thinking: full_thinking,
        };

        Ok(ChatMessageResponse {
            model,
            created_at,
            message: msg,
            logprobs: None,
            done: true,
            final_data,
        })
    }

    /// Apply optional settings to request
    fn apply_optional_settings(&self, mut request: ChatMessageRequest) -> ChatMessageRequest {
        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        request
    }

    /// Build a request from current history with ephemeral messages prepended
    fn build_request(&self) -> ChatMessageRequest {
        // Build messages: ephemeral first, then history
        let mut messages =
            Vec::with_capacity(self.ephemeral_messages.len() + self.history.messages().len());
        messages.extend(self.ephemeral_messages.iter().cloned());
        messages.extend(self.history.messages().iter().cloned());

        let mut request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Add tools - need to convert our CustomToolInfo to ollama-rs's ToolInfo
        // We serialize ours and it's compatible. If serialization fails, log
        // the error and fall back to an empty tools list (fail-safe: better to
        // send a request without tools than to panic). See AGENTS.md steering
        // rule: every silent fallback MUST have a log companion.
        let tools_json = serde_json::to_string(&self.tool_infos).unwrap_or_else(|e| {
            log::error!("Failed to serialize tool_infos for request: {e}");
            String::new()
        });
        let tools: Vec<ollama_rs::generation::tools::ToolInfo> = serde_json::from_str(&tools_json)
            .unwrap_or_else(|e| {
                log::error!("Failed to deserialize tool_infos from JSON: {e}");
                Vec::new()
            });
        request = request.tools(tools);

        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        request
    }

    /// Process response, handling tool calls with event emission.
    ///
    /// `already_streamed` should be `true` when the content was already
    /// streamed via `chat_stream()` — this prevents emitting an extra
    /// `PreToolContent` event that would duplicate the text. With W2 #122,
    /// all ReAct turns stream, so the only remaining non-streaming call site
    /// is `chat()` (terminal/CLI query path).
    async fn process_response(
        &mut self,
        resp: ChatMessageResponse,
        already_streamed: bool,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check if there are tool calls
        if !resp.message.tool_calls.is_empty() {
            // Accumulate pre-tool content if present
            let has_content = !resp.message.content.trim().is_empty();
            let has_thinking = resp.message.thinking.is_some();

            if has_content || has_thinking {
                // W2 #122: pre-tool content is accumulated only when it was
                // already streamed via chat_stream(). send_message_stream()
                // uses take_pre_tool_content() to compute post_tool_content
                // (final response minus pre-tool prefix) and emit StreamBlockDone.
                if already_streamed {
                    if !resp.message.content.trim().is_empty() {
                        if !self.pre_tool_content.is_empty() {
                            self.pre_tool_content.push_str("\n\n");
                        }
                        self.pre_tool_content.push_str(&resp.message.content);
                    }
                    // Accumulate thinking (use the first one)
                    if self.pre_tool_thinking.is_none() {
                        self.pre_tool_thinking = resp.message.thinking.clone();
                    }
                }

                // Emit event so callers can display pre-tool text in the
                // terminal/CLI path. In streaming TUI mode the content is
                // already on screen, so the listener skips it via
                // `already_streamed`.
                self.emit_event(ChatEvent::PreToolContent {
                    content: resp.message.content.clone(),
                    thinking: resp.message.thinking.clone(),
                });
            }

            // Push assistant message to history (with tool calls).
            // Sanitize invalid tool_call arguments BEFORE persisting: when
            // the provider sends malformed JSON (e.g., MiniMax M3 concatenates
            // multiple objects like {"a":1}{"b":2}), the parser falls back to
            // Value::String(raw). If we persist that, the next request
            // includes the invalid arguments and the provider rejects with
            // HTTP 400 "invalid tool call arguments", breaking the ReAct loop.
            // Replace Value::String with Value::Object({}) so the next
            // request sends valid (empty) arguments instead.
            let mut sanitized_message = resp.message.clone();
            let mut had_invalid_args = false;
            for tc in &mut sanitized_message.tool_calls {
                if matches!(tc.function.arguments, serde_json::Value::String(_)) {
                    log::warn!(
                        "Sanitizing invalid tool call arguments for '{}': \
                         replacing Value::String (malformed JSON) with empty Object",
                        tc.function.name
                    );
                    tc.function.arguments = serde_json::Value::Object(serde_json::Map::new());
                    had_invalid_args = true;
                }
            }
            if had_invalid_args {
                log::debug!(
                    "Sanitized {} tool call(s) with invalid arguments \
                     before persisting to history",
                    sanitized_message.tool_calls.len()
                );
            }
            self.history.push(sanitized_message);

            // Execute each tool call
            let mut tools_executed = Vec::new();

            for (call_idx, call) in resp.message.tool_calls.clone().into_iter().enumerate() {
                // Check for user cancellation before each tool call.
                // When Ctrl+C is pressed during multi-tool execution,
                // the cancel token is set and we stop the loop after
                // the current tool finishes — not between tokens.
                if let Some(ref ct) = self.cancel_token
                    && ct.is_cancelled()
                {
                    log::debug!(
                        "Tool loop cancelled by user after {} tools",
                        tools_executed.len()
                    );
                    return Err(ollama_rs::error::OllamaError::Other(
                        CANCELLED_BY_USER.to_string(),
                    ));
                }

                let tool_name = call.function.name.clone();
                let args = call.function.arguments.clone();
                // Prefer the tool_call_id emitted by the provider so it
                // matches the streaming preview. When the stream id is empty,
                // fall back to a synthetic id so tool calls stay unique
                // across ReAct rounds.
                self.tool_call_counter += 1;
                let tool_call_id = match self.stream_tool_call_ids.get(call_idx) {
                    Some(stream_id) if !stream_id.is_empty() => stream_id.clone(),
                    _ => format!("{tool_name}_{}", self.tool_call_counter),
                };

                log::debug!("Tool call: {:?}", call.function);

                self.emit_event(ChatEvent::ToolExecutionStarted {
                    tool_call_id: tool_call_id.clone(),
                    name: tool_name.clone(),
                    args: args.clone(),
                });

                let Some(tool) = self.tools.get_mut(&tool_name) else {
                    log::debug!(
                        "Unknown tool '{}'. Available: {}",
                        tool_name,
                        self.tools.keys().cloned().collect::<Vec<_>>().join(", ")
                    );
                    return Err(ollama_rs::error::OllamaError::ToolCallError(
                        ollama_rs::error::ToolCallError::UnknownToolName,
                    ));
                };

                let result = match tool.call(args.clone()).await {
                    Ok(result) => {
                        // Tools follow the convention "always return Ok(String)"
                        // (AGENTS.md: "Tools must NEVER crash"). When the string
                        // indicates an error, it's a soft error — the LLM still
                        // receives it as a tool message and can self-correct, but
                        // we flag is_error=true so the TUI can show a visual
                        // indicator (✗ prefix instead of 🔧).
                        let is_error = is_tool_error(&result);
                        self.emit_event(ChatEvent::ToolExecutionFinished {
                            tool_call_id: tool_call_id.clone(),
                            result: result.clone(),
                            is_error,
                        });
                        result
                    }
                    Err(e) => {
                        log::warn!("Tool '{}' execution failed: {e}", tool_name);
                        log::debug!(
                            "  Arguments: {}",
                            serde_json::to_string(&args).unwrap_or_else(|_| args.to_string())
                        );
                        // W2 Wave Context (#116): Tool execution errors are now
                        // recoverable — push the error as a tool message so the
                        // LLM can self-correct within the same turn instead of
                        // aborting the conversation.
                        let error_msg = format!(
                            "Error executing tool '{tool_name}': {e}. \
                             Please try again with different arguments or use a different approach."
                        );
                        self.emit_event(ChatEvent::ToolExecutionFinished {
                            tool_call_id: tool_call_id.clone(),
                            result: error_msg.clone(),
                            is_error: true,
                        });
                        self.history.push(ChatMessage::tool(error_msg));
                        tools_executed.push(tool_name.clone());
                        continue;
                    }
                };

                log::debug!("Tool response: {}", &result);

                // Inter-tool context check: detect overflow and truncate if needed
                let check_result = self.check_and_handle_context_overflow(result);

                // Check if compaction is needed - stop and emit event
                if check_result.needs_compaction {
                    // Push the current result to history before stopping
                    self.history.push(ChatMessage::tool(check_result.result));
                    tools_executed.push(tool_name);

                    // Emit compaction needed event
                    self.emit_event(ChatEvent::ContextNeedsCompaction {
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                        tools_executed: tools_executed.clone(),
                    });

                    // Return error to signal compaction needed
                    let tools_str = tools_executed.join(", ");
                    return Err(ollama_rs::error::OllamaError::Other(format!(
                        "CONTEXT_NEEDS_COMPACT:{}:{}:{}",
                        check_result.tokens_used,
                        self.context_window.unwrap_or(0),
                        tools_str
                    )));
                }

                // Emit context events
                if check_result.was_truncated {
                    let result_tokens = estimate_tokens(&check_result.result);
                    self.emit_event(ChatEvent::ContextTruncated {
                        tool_name: tool_name.clone(),
                        original_tokens: check_result.tokens_used,
                        new_tokens: result_tokens,
                        context_window: self.context_window.unwrap_or(0),
                    });
                } else if check_result.is_near_limit {
                    self.emit_event(ChatEvent::ContextNearLimit {
                        tool_name: tool_name.clone(),
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                    });
                }

                // Push (possibly truncated) result to history
                self.history.push(ChatMessage::tool(check_result.result));
                tools_executed.push(tool_name);
            }

            // Recurse to get next response using streaming.
            Box::pin(self.process_next_stream()).await
        } else {
            // No tool calls - this is the final response
            // Push to history
            self.history.push(resp.message.clone());

            Ok(resp)
        }
    }

    /// Process next response after tool calls, using streaming.
    async fn process_next_stream(&mut self) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check for user cancellation before making next request
        if let Some(ref ct) = self.cancel_token
            && ct.is_cancelled()
        {
            log::debug!("process_next_stream cancelled by user");
            return Err(ollama_rs::error::OllamaError::Other(
                CANCELLED_BY_USER.to_string(),
            ));
        }

        // Context overflow check (same as the previous non-streaming path).
        if let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) {
            let usage = match self.real_history_tokens {
                Some(tokens) => ContextUsage::from_api_usage(tokens as u32, prompt, 0),
                None => {
                    log::debug!(
                        "[process_next_stream] No real_history_tokens; falling back to estimate"
                    );
                    let messages = self.history.messages();
                    let system = estimate_tokens(prompt) + MESSAGE_OVERHEAD;
                    let history: usize = messages
                        .iter()
                        .map(|m| estimate_tokens(&m.content) + MESSAGE_OVERHEAD)
                        .sum();
                    ContextUsage {
                        system_tokens: system,
                        tools_tokens: 0,
                        history_tokens: history,
                        total_tokens: system + history,
                        source: crate::tokens::ContextSource::Estimated,
                    }
                }
            };

            let (_, _, _, emergency_threshold) = calculate_thresholds(ctx_window);
            let threshold = ctx_window.saturating_sub(emergency_threshold);

            if usage.total_tokens > threshold {
                let msg = format!(
                    "Context overflow during tool execution: {} tokens used, {} available. Use /compact to reduce context.",
                    usage.total_tokens, ctx_window
                );
                return Err(ollama_rs::error::OllamaError::Other(msg));
            }
        }

        let request = self.build_request();
        let response = match self.stream_turn(request).await {
            Ok(resp) => resp,
            Err(e) => {
                let error_str = e.to_string();
                if error_str.contains("invalid tool call arguments") {
                    // Provider rejected malformed tool call arguments (JSON
                    // invalid). Push tool error message and retry — the Fix A
                    // sanitization already replaced Value::String args with
                    // empty Object, so the next request should be accepted.
                    self.react_retry_count += 1;
                    if self.react_retry_count > 3 {
                        log::warn!(
                            "Provider rejected tool call arguments {} times — \
                             giving up to avoid infinite loop",
                            self.react_retry_count
                        );
                        return Err(e);
                    }
                    log::debug!(
                        "Provider rejected tool call arguments (attempt {}/3) — \
                         pushing error as tool message and retrying",
                        self.react_retry_count
                    );
                    let recovery_msg = format!(
                        "Error: The provider rejected the tool call arguments \
                         as invalid. This usually means the arguments were \
                         malformed JSON or had missing/invalid fields. \
                         Please try again with valid arguments.\n\n\
                         Provider error: {error_str}"
                    );
                    self.history.push(ChatMessage::tool(recovery_msg));
                    let request = self.build_request();
                    self.stream_turn(request).await?
                } else if error_str.contains("Timeout:") {
                    // WORKAROUND (TODO #123): string sniffing for timeout errors.
                    //
                    // Two timeout sources exist:
                    //   1. Sprachspiel's idle_timeout: "Timeout: SSE stream idle
                    //      timeout after 300s" (from parse_sse_stream)
                    //   2. reqwest's read_timeout: "Timeout: error decoding
                    //      response body" (from ReadTimeoutBody, when the HTTP
                    //      read_timeout fires before the idle_timeout)
                    //
                    // Both are retryable — the provider accepted the connection
                    // but didn't produce chunks in time (under load, long
                    // prefill after large tool results, etc.).
                    //
                    // TODO #123: eliminate this string sniffing. The proper fix
                    // is to migrate stream_turn to return ProviderError directly
                    // (instead of OllamaError via convert_provider_error), then
                    // use `err.retry_category()` which type-safely maps
                    // ProviderError::Timeout → NetworkRetry. This eliminates
                    // the convert_provider_error layer and all string matching.
                    // See comments in ollama_shim.rs:479, retry.rs:107, and
                    // IMPLEMENTATION.md #123 open topics.
                    self.react_retry_count += 1;
                    if self.react_retry_count > 3 {
                        log::warn!(
                            "Stream timed out {} times in ReAct loop — \
                             giving up to avoid infinite loop",
                            self.react_retry_count
                        );
                        return Err(e);
                    }
                    log::debug!(
                        "Stream timeout in ReAct loop (attempt {}/3): {error_str} — retrying",
                        self.react_retry_count
                    );
                    let recovery_msg = "Error: The request timed out after the provider accepted \
                         the connection but did not produce any output. \
                         The provider may be under load or processing a large \
                         context. Please continue from where you left off.";
                    self.history
                        .push(ChatMessage::tool(recovery_msg.to_string()));
                    let request = self.build_request();
                    self.stream_turn(request).await?
                } else {
                    return Err(e);
                }
            }
        };

        // Reset retry counter on success
        self.react_retry_count = 0;

        // Continue the ReAct loop: if more tool calls arrive, execute them.
        if response.message.tool_calls.is_empty() {
            Ok(response)
        } else {
            self.process_response(response, /*already_streamed=*/ true)
                .await
        }
    }
}

/// Heuristic: detect whether a tool result string represents an error.
///
/// Tools follow the convention "always return Ok(String)" (AGENTS.md: "Tools
/// must NEVER crash"). Error messages use various prefixes depending on the
/// tool and the error path (validate_path, blocklist, file ops, etc.).
/// This function checks the common error prefixes so the coordinator can flag
/// `is_error=true` and the TUI can show a visual indicator (✗ prefix).
fn is_tool_error(result: &str) -> bool {
    // Trim leading whitespace — some tools may have leading spaces.
    let trimmed = result.trim_start();
    // Common error prefixes used across all tools.
    trimmed.starts_with("Error:")
        || trimmed.starts_with("Access denied:")
        || trimmed.starts_with("FILE NOT FOUND:")
        || trimmed.starts_with("NOT A FILE:")
        || trimmed.starts_with("NOT A DIRECTORY:")
        || trimmed.starts_with("BLOCKED:")
        || trimmed.starts_with("Error executing tool")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_continuation_tag_basic() {
        let content = r#"I've analyzed the first part. Let me continue.

<continuation_needed>
Reasoning paused: Analyzed file structure
Next step: Examine the main function
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Analyzed file structure");
        assert_eq!(tag.next_step, "Examine the main function");
        assert!(cleaned.contains("I've analyzed the first part"));
        assert!(!cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_multiline() {
        let content = r#"Some response here.

<continuation_needed>
Reasoning paused: Completed step 1
Next step: Process step 2
</continuation_need>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none(), "Should not parse without closing tag");
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_in_code_block() {
        let content = r#"Here's an example:

```
<continuation_needed>
Reasoning paused: In code block
Next step: Should not parse
</continuation_needed>
```

This should not be parsed as a continuation tag."#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(
            tag.is_none(),
            "Tags inside code blocks should not be parsed"
        );
        assert!(cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_empty_fields() {
        let content = r#"<continuation_needed>
Reasoning paused:
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Empty fields should return None
        assert!(tag.is_none());
    }

    #[test]
    fn test_parse_continuation_tag_partial_fields() {
        let content = r#"<continuation_needed>
Reasoning paused: Half way through analysis
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Should still parse if at least one field is filled
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Half way through analysis");
        assert!(tag.next_step.is_empty());
    }

    #[test]
    fn test_parse_continuation_tag_no_tag() {
        let content = "This is a normal response without any continuation tag.";

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none());
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_nested_tags() {
        // Nested tags shouldn't happen in practice, but if they do,
        // we parse from first open to first close and take the last matching values
        let content = r#"<continuation_needed>
Reasoning paused: First level
Next step: Second level
<continuation_needed>
Reasoning paused: Nested
Next step: Should ignore
</continuation_needed>
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // We find the first </continuation_needed> (after "ignore")
        // and parse the content between, which includes all lines
        // The last matching field values win
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Nested"); // Last "Reasoning paused:" wins
        assert_eq!(tag.next_step, "Should ignore"); // Last "Next step:" wins
    }

    #[test]
    fn test_is_tool_error_detects_common_prefixes() {
        assert!(is_tool_error("Error: File not found"));
        assert!(is_tool_error("Access denied: path not accessible"));
        assert!(is_tool_error("FILE NOT FOUND: '/tmp/missing.txt'. ..."));
        assert!(is_tool_error("NOT A FILE: '/tmp'. ..."));
        assert!(is_tool_error("NOT A DIRECTORY: '/tmp/file'. ..."));
        assert!(is_tool_error("BLOCKED: '/tmp/.env'. ..."));
        assert!(is_tool_error("Error executing tool 'read_file': ..."));
        // Leading whitespace is trimmed
        assert!(is_tool_error("  Error: indented"));
        // Success cases are NOT errors
        assert!(!is_tool_error("file1.txt\nfile2.txt"));
        assert!(!is_tool_error("Contents of the file..."));
        assert!(!is_tool_error("Task 1 marked as in_progress"));
        assert!(!is_tool_error(""));
    }

    #[test]
    fn test_sanitizes_invalid_tool_call_arguments() {
        // Simulate a model that sends malformed JSON as tool call arguments
        // (e.g., MiniMax M3 concatenates multiple objects: {"a":1}{"b":2}).
        // The parser falls back to Value::String(raw). The coordinator should
        // sanitize this to Value::Object({}) before persisting to history,
        // so the next request doesn't get rejected with HTTP 400.
        use ollama_rs::generation::chat::ChatMessage;
        use ollama_rs::generation::chat::MessageRole;
        use ollama_rs::generation::tools::{ToolCall, ToolCallFunction};

        let msg = ChatMessage {
            role: MessageRole::Assistant,
            content: String::new(),
            tool_calls: vec![
                ToolCall {
                    function: ToolCallFunction {
                        name: "todo_add".to_string(),
                        // Malformed: multiple JSON objects concatenated
                        arguments: serde_json::Value::String(
                            r#"{"description":"task1","priority":"high"}{"description":"task2"}"#
                                .to_string(),
                        ),
                    },
                },
                ToolCall {
                    function: ToolCallFunction {
                        name: "read_file".to_string(),
                        // Valid JSON
                        arguments: serde_json::json!({"path": "test.txt"}),
                    },
                },
            ],
            images: None,
            thinking: None,
        };

        // Apply the same sanitization logic as process_response
        let mut sanitized = msg.clone();
        for tc in &mut sanitized.tool_calls {
            if matches!(tc.function.arguments, serde_json::Value::String(_)) {
                tc.function.arguments = serde_json::Value::Object(serde_json::Map::new());
            }
        }

        // The invalid one should be sanitized
        assert_eq!(
            sanitized.tool_calls[0].function.arguments,
            serde_json::Value::Object(serde_json::Map::new()),
            "Invalid Value::String args should be sanitized to empty Object"
        );
        // The valid one should be preserved
        assert_eq!(
            sanitized.tool_calls[1].function.arguments,
            serde_json::json!({"path": "test.txt"}),
            "Valid args should be preserved"
        );
    }
}
