//! Custom Coordinator with callbacks for intermediate content
//!
//! This is our own implementation that provides:
//! - Pre-tool content callbacks (content before tool calls)
//! - Thinking content callbacks
//! - Full control over tool execution flow
//! - Inter-tool context overflow detection

/// Error string returned when the user cancels tool execution (Ctrl+C).
/// Checked by the caller (`handle_user_message_stream`) to suppress error display.
pub const CANCELLED_BY_USER: &str = "CANCELLED_BY_USER";

use std::{collections::HashMap, future::Future, pin::Pin};

use ollama_rs::re_exports::serde::{Deserialize, Serialize, de::DeserializeOwned};
use ollama_rs::{
    Ollama,
    generation::{
        chat::{ChatMessage, ChatMessageResponse, request::ChatMessageRequest},
        parameters::ThinkType,
        tools::Tool,
    },
    history::ChatHistory,
    models::ModelOptions,
    re_exports::schemars::{JsonSchema, Schema, generate::SchemaSettings},
};
use serde_json::Value;

use crate::context_overflow::{
    calculate_available_budget, calculate_thresholds, estimate_chat_messages_tokens,
    is_emergency_context, needs_inter_tool_compaction,
};
use crate::tokens::{MESSAGE_OVERHEAD, estimate_tokens};
use crate::utils::truncate_to_budget;

/// Result type for tool execution
pub type ToolResult = std::result::Result<String, Box<dyn std::error::Error + Send + Sync>>;

/// Trait to hold and call tools - our own implementation since ollama-rs's ToolHolder is private
pub trait ToolHolder: Send + Sync {
    fn call(
        &mut self,
        parameters: Value,
    ) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send + Sync>>;
}

impl<T: Tool> ToolHolder for T {
    fn call(
        &mut self,
        parameters: Value,
    ) -> Pin<Box<dyn Future<Output = ToolResult> + '_ + Send + Sync>> {
        Box::pin(async move {
            // Handle different JSON formats that models might return
            let param_value =
                match serde_json::from_value::<ToolCallFunctionParser>(parameters.clone()) {
                    Ok(func) => func.arguments,
                    Err(_) => parameters,
                };

            let params: T::Params = serde_json::from_value(param_value)?;
            T::call(self, params).await
        })
    }
}

/// Helper struct for parsing tool call function JSON
#[derive(Deserialize)]
struct ToolCallFunctionParser {
    #[expect(dead_code)]
    name: String,
    arguments: Value,
}

/// Tool type enum
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CustomToolType {
    #[serde(rename_all(deserialize = "PascalCase"))]
    Function,
}

/// Tool function info
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolFunctionInfo {
    pub name: String,
    pub description: String,
    pub parameters: Schema,
}

/// Our own ToolInfo since ollama-rs's ToolInfo::new is private
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CustomToolInfo {
    #[serde(rename = "type")]
    pub tool_type: CustomToolType,
    pub function: CustomToolFunctionInfo,
}

impl CustomToolInfo {
    /// Create a new ToolInfo for a given Tool type
    pub fn new<P: DeserializeOwned + JsonSchema, T: Tool<Params = P>>() -> Self {
        let mut settings = SchemaSettings::draft07();
        settings.inline_subschemas = true;
        let generator = settings.into_generator();

        let parameters = generator.into_root_schema_for::<P>();

        Self {
            tool_type: CustomToolType::Function,
            function: CustomToolFunctionInfo {
                name: T::name().to_string(),
                description: T::description().to_string(),
                parameters,
            },
        }
    }
}

/// Pre-tool content accumulated during processing
///
/// Contains text generated by the assistant before tool calls,
/// which should be saved separately from the final response.
#[derive(Debug, Clone, Default)]
pub struct PreToolContent {
    /// Content generated before tool calls
    pub content: String,
    /// Thinking content (if any)
    pub thinking: Option<String>,
}

/// Continuation tag parsed from LLM response
///
/// When the LLM detects context is nearly full and needs to pause,
/// it emits this tag with checkpoint information for resumption.
#[derive(Debug, Clone)]
pub struct ContinuationTag {
    /// Where reasoning was paused
    pub paused_at: String,
    /// What the LLM was about to do next
    pub next_step: String,
}

/// Parse continuation tag from LLM response
///
/// Extracts the <continuation_needed> tag content and returns
/// both the cleaned response (without the tag) and the parsed tag.
///
/// Returns (cleaned_content, Some(tag)) if tag found and parsed,
/// or (original_content, None) if no tag or invalid.
pub fn parse_continuation_tag(content: &str) -> (String, Option<ContinuationTag>) {
    // Find the tag
    let start_tag = "<continuation_needed>";
    let end_tag = "</continuation_needed>";

    let start_pos = match content.find(start_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Check if tag is inside a code block (should NOT be parsed)
    let before_tag = &content[..start_pos];
    let code_block_count = before_tag.matches("```").count();
    if code_block_count % 2 == 1 {
        // Inside a code block, don't parse
        return (content.to_string(), None);
    }

    let end_pos = match content.find(end_tag) {
        Some(pos) => pos,
        None => return (content.to_string(), None),
    };

    // Extract tag content
    let tag_content = &content[start_pos + start_tag.len()..end_pos];

    // Parse fields
    let mut paused_at = String::new();
    let mut next_step = String::new();

    for line in tag_content.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("Reasoning paused:") {
            paused_at = value.trim().to_string();
        } else if let Some(value) = line.strip_prefix("Next step:") {
            next_step = value.trim().to_string();
        }
    }

    // Create cleaned content by removing the tag
    let cleaned = format!(
        "{}{}",
        &content[..start_pos],
        &content[end_pos + end_tag.len()..]
    );

    // Normalize whitespace in cleaned content
    let cleaned = cleaned.trim().to_string();

    // Require at least one field to be filled
    if paused_at.is_empty() && next_step.is_empty() {
        return (content.to_string(), None);
    }

    (
        cleaned,
        Some(ContinuationTag {
            paused_at,
            next_step,
        }),
    )
}

/// Event emitted during chat processing
#[derive(Debug, Clone)]
pub enum ChatEvent {
    /// Content generated before tool calls (often thinking/intro text).
    /// `already_streamed` is `true` when the content was already emitted
    /// via streaming tokens (e.g. first tool-call round); `false` when it
    /// comes from a non-streaming path such as `process_next()`.
    PreToolContent {
        content: String,
        thinking: Option<String>,
        already_streamed: bool,
    },
    /// Context is near limit after tool execution (inter-tool threshold)
    /// Indicates compaction may be needed before next tool
    ContextNearLimit {
        tool_name: String,
        tokens_used: usize,
        context_window: usize,
    },
    /// Context was truncated during tool execution (emergency threshold)
    /// Indicates last tool result was truncated to fit
    ContextTruncated {
        tool_name: String,
        original_tokens: usize,
        new_tokens: usize,
        context_window: usize,
    },
    /// Context needs compaction during tool execution (compaction threshold)
    /// Signals that tool execution should pause for compaction
    ContextNeedsCompaction {
        tokens_used: usize,
        context_window: usize,
        tools_executed: Vec<String>,
    },
}

/// Result of checking context overflow after tool execution
struct ContextCheckResult {
    /// The result to use (possibly truncated)
    result: String,
    /// Whether context is near limit (inter-tool threshold)
    is_near_limit: bool,
    /// Whether result was truncated (emergency threshold)
    was_truncated: bool,
    /// Tokens used (for events)
    tokens_used: usize,
    /// Whether compaction is needed before continuing
    needs_compaction: bool,
}

/// A coordinator for managing chat interactions with event callbacks.
pub struct CustomCoordinator<C: ChatHistory> {
    model: String,
    ollama: Ollama,
    options: ModelOptions,
    history: C,
    tool_infos: Vec<CustomToolInfo>,
    tools: HashMap<String, Box<dyn ToolHolder>>,
    think: Option<ThinkType>,
    /// Callback for events
    event_callback: Option<Box<dyn Fn(ChatEvent) + Send + Sync>>,
    /// Context window size for overflow detection during tool execution
    context_window: Option<usize>,
    /// System prompt for token estimation
    system_prompt: Option<String>,
    /// Real token count from Ollama's prompt_eval_count (if available)
    /// This is the ACTUAL token count, not an estimation.
    /// Should always be used when available for accurate overflow detection.
    real_history_tokens: Option<usize>,
    /// Number of messages in history at the start of this request.
    /// Used to distinguish between session history (base) and new messages (growth).
    initial_message_count: usize,
    /// Accumulated pre-tool content (text generated before tool calls)
    pre_tool_content: String,
    pre_tool_thinking: Option<String>,
    /// Ephemeral messages (not persisted to history)
    /// Used for continuation prompts after context compaction
    ephemeral_messages: Vec<ChatMessage>,
    /// Cancellation token for aborting tool execution mid-loop.
    /// When cancelled, the tool loop stops after the current tool finishes
    /// and returns an error that the caller interprets as user cancellation.
    cancel_token: Option<tokio_util::sync::CancellationToken>,
}

impl<C: ChatHistory> CustomCoordinator<C> {
    /// Creates a new `CustomCoordinator` instance.
    pub fn new(ollama: Ollama, model: String, history: C) -> Self {
        Self {
            model,
            ollama,
            options: ModelOptions::default(),
            history,
            tool_infos: Vec::default(),
            tools: HashMap::default(),
            think: None,
            event_callback: None,
            context_window: None,
            system_prompt: None,
            real_history_tokens: None,
            initial_message_count: 0,
            pre_tool_content: String::new(),
            pre_tool_thinking: None,
            ephemeral_messages: Vec::new(),
            cancel_token: None,
        }
    }

    /// Check context overflow and handle truncation if needed
    ///
    /// Returns a ContextCheckResult with the (possibly truncated) result and status flags.
    fn check_and_handle_context_overflow(&self, result: String) -> ContextCheckResult {
        let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) else {
            log::debug!("check_and_handle_context_overflow: no context_window or system_prompt");
            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: 0,
                needs_compaction: false,
            };
        };

        // Calculate total tokens:
        // 1. real_history_tokens: Base from session (Ollama's prompt_eval_count) - EXACT
        // 2. growth_tokens: New messages during this request (assistant + tool results) - ESTIMATED
        // 3. system_tokens: System prompt
        // 4. tool_tokens: Tool definitions
        // 5. result_tokens: Current tool result being processed

        // Base: Real tokens from Ollama (includes all session history)
        let base_tokens = self.real_history_tokens.unwrap_or(0);

        // Growth: ONLY messages added during this request (avoid double-counting with base)
        // Messages from initial_message_count onwards are NEW in this request
        let all_messages = self.history.messages().len();
        let growth_messages = &self.history.messages()[self.initial_message_count..];
        let growth_tokens = estimate_chat_messages_tokens(growth_messages);

        // Tool definitions (each tool: name + description + parameters + overhead)
        // NOTE: These are already included in base_tokens from Ollama's prompt_eval_count
        // We calculate them separately only for diagnostic purposes
        let tool_tokens: usize = self
            .tool_infos
            .iter()
            .map(|info| {
                let name_tokens = estimate_tokens(&info.function.name);
                let desc_tokens = estimate_tokens(&info.function.description);
                let params_tokens = estimate_tokens(
                    &serde_json::to_string(&info.function.parameters).unwrap_or_default(),
                );
                name_tokens + desc_tokens + params_tokens + MESSAGE_OVERHEAD
            })
            .sum();

        // System prompt tokens - also included in base_tokens from Ollama
        let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;

        // Result tokens - the current tool result being processed
        let result_tokens = estimate_tokens(&result);

        // IMPORTANT: base_tokens from Ollama's prompt_eval_count ALREADY includes:
        // - System prompt tokens
        // - Tool definition tokens
        // - All history tokens
        //
        // So we should NOT add tool_tokens and system_tokens again!
        // Only add: growth_tokens (new in this request) + result_tokens (current result)
        let total_after_add = base_tokens + growth_tokens + result_tokens;

        // Format token values: show as raw number if < 1000, otherwise as NK
        fn fmt_tokens(v: usize) -> String {
            if v >= 1000 {
                format!("{}K", v / 1000)
            } else {
                format!("{}", v)
            }
        }

        let (_, compaction_buffer, _, _) = calculate_thresholds(ctx_window);

        // Debug log (only when debug enabled)
        log::debug!("[INTER-TOOL-CHECK-DETAILS]");
        log::debug!(
            "  base_tokens={} (from the LLM server, includes sys+tools+history)",
            base_tokens
        );
        log::debug!("  initial_message_count={}", self.initial_message_count);
        log::debug!("  all_messages={}", all_messages);
        log::debug!(
            "  growth_messages={} (new this request)",
            growth_messages.len()
        );
        log::debug!("  growth_tokens={} (estimated)", growth_tokens);
        log::debug!(
            "  tool_tokens={} (diagnostic, already in base)",
            tool_tokens
        );
        log::debug!(
            "  system_tokens={} (diagnostic, already in base)",
            system_tokens
        );
        log::debug!("  result_tokens={} (current tool result)", result_tokens);
        log::debug!(
            "[INTER-TOOL-CHECK] total={}/{} remaining={} buffer={}",
            fmt_tokens(total_after_add),
            fmt_tokens(ctx_window),
            fmt_tokens(ctx_window.saturating_sub(total_after_add)),
            fmt_tokens(compaction_buffer)
        );

        if is_emergency_context(total_after_add, ctx_window) {
            let available = calculate_available_budget(base_tokens + growth_tokens, ctx_window);
            let original_tokens = estimate_tokens(&result);
            let truncated = truncate_to_budget(&result, available);
            let truncated_tokens = estimate_tokens(&truncated);
            let reduction = original_tokens.saturating_sub(truncated_tokens);

            // Only show truncation warning if significant reduction
            if reduction > 100 || (original_tokens > 1000 && reduction * 100 / original_tokens > 10)
            {
                log::warn!(
                    "[EMERGENCY] Context at {}% ({} tokens). Truncated tool result: {} → {} tokens",
                    (total_after_add) * 100 / ctx_window,
                    total_after_add,
                    original_tokens,
                    truncated_tokens
                );
            }

            return ContextCheckResult {
                result: truncated,
                is_near_limit: true,
                was_truncated: reduction > 0,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        let remaining = ctx_window.saturating_sub(total_after_add);
        if remaining < compaction_buffer {
            // Only trigger compaction if there's history to compact
            // base_tokens == 0 means fresh session with no messages to summarize
            if base_tokens == 0 {
                // Fresh session - nothing to compact, just proceed
                // Context will grow as conversation proceeds, future requests will have base > 0
                log::debug!(
                    "[INTER-TOOL] Fresh session (base=0), nothing to compact. Proceeding... ({}K/{}K)",
                    total_after_add / 1000,
                    ctx_window / 1000
                );
                return ContextCheckResult {
                    result,
                    is_near_limit: true,
                    was_truncated: false,
                    tokens_used: total_after_add,
                    needs_compaction: false,
                };
            }

            log::warn!(
                "⏳ [INTER-TOOL] Context: {}K/{}K ({}% used, {}K remaining). Buffer: {}K. NEEDS COMPACTION.",
                total_after_add / 1000,
                ctx_window / 1000,
                (total_after_add * 100) / ctx_window,
                remaining / 1000,
                compaction_buffer / 1000
            );

            return ContextCheckResult {
                result,
                is_near_limit: true,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: true,
            };
        }

        if needs_inter_tool_compaction(total_after_add, ctx_window) {
            log::debug!(
                "[INFO] Context at {}% ({} tokens). Inter-tool warning.",
                (total_after_add) * 100 / ctx_window,
                total_after_add
            );

            return ContextCheckResult {
                result,
                is_near_limit: false,
                was_truncated: false,
                tokens_used: total_after_add,
                needs_compaction: false,
            };
        }

        ContextCheckResult {
            result,
            is_near_limit: false,
            was_truncated: false,
            tokens_used: total_after_add,
            needs_compaction: false,
        }
    }

    /// Set the context window size for overflow detection
    pub fn context_window(mut self, context_window: usize) -> Self {
        self.context_window = Some(context_window);
        self
    }

    /// Set the system prompt for token estimation
    pub fn system_prompt(mut self, system_prompt: String) -> Self {
        self.system_prompt = Some(system_prompt);
        self
    }

    /// Set the real history token count from Ollama's prompt_eval_count.
    /// This should ALWAYS be used when available for accurate overflow detection.
    /// Estimation is a fallback when real tokens are not available.
    pub fn real_history_tokens(mut self, tokens: usize) -> Self {
        self.real_history_tokens = Some(tokens);
        self
    }

    /// Add a tool to the coordinator
    pub fn add_tool<T: Tool + 'static>(mut self, tool: T) -> Self {
        self.tool_infos.push(CustomToolInfo::new::<T::Params, T>());
        self.tools.insert(T::name().to_string(), Box::new(tool));
        self
    }

    /// Set the format (for future use)
    /// Set model options
    pub fn options(mut self, options: ModelOptions) -> Self {
        self.options = options;
        self
    }

    /// Set think mode
    pub fn think(mut self, think: impl Into<ThinkType>) -> Self {
        self.think = Some(think.into());
        self
    }

    /// Set event callback for receiving intermediate content and events
    pub fn on_event(mut self, callback: impl Fn(ChatEvent) + Send + Sync + 'static) -> Self {
        self.event_callback = Some(Box::new(callback));
        self
    }

    /// Extract accumulated pre-tool content
    ///
    /// Returns the content generated before tool calls and clears the accumulator.
    /// This should be called after `chat()` returns to get any pre-tool content.
    pub fn take_pre_tool_content(&mut self) -> Option<PreToolContent> {
        if self.pre_tool_content.is_empty() {
            return None;
        }
        Some(PreToolContent {
            content: std::mem::take(&mut self.pre_tool_content),
            thinking: self.pre_tool_thinking.take(),
        })
    }

    /// Add an ephemeral message (not persisted to history)
    ///
    /// Ephemeral messages are prepended to requests but never saved.
    /// Used for continuation prompts after context compaction.
    pub fn push_ephemeral(&mut self, message: ChatMessage) {
        self.ephemeral_messages.push(message);
    }

    /// Set the cancellation token for tool loop interruption.
    ///
    /// When the token is cancelled, the tool execution loop stops after
    /// the current tool finishes and returns an error. The caller
    /// (event loop) interprets this as user-initiated cancellation.
    pub fn cancel_token(mut self, token: tokio_util::sync::CancellationToken) -> Self {
        self.cancel_token = Some(token);
        self
    }

    /// Emit an event if callback is set
    fn emit_event(&self, event: ChatEvent) {
        if let Some(ref callback) = self.event_callback {
            callback(event);
        }
    }

    /// Send a chat message and process tool calls with event emission
    pub async fn chat(
        &mut self,
        messages: Vec<ChatMessage>,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        for m in &messages {
            log::debug!("Hit {} with:", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        let request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Apply optional settings
        let request = self.apply_optional_settings(request);

        // Push initial messages to history
        for m in request.messages.clone() {
            self.history.push(m);
        }

        // Store how many messages we started with (to distinguish base from growth)
        self.initial_message_count = self.history.messages().len();

        // Make the request
        let resp = self.ollama.send_chat_messages(self.build_request()).await?;

        // Process the response (non-streaming path — content was not streamed)
        self.process_response(resp, /*already_streamed=*/ false)
            .await
    }

    /// Send a chat message with streaming and process tool calls.
    ///
    /// This is the streaming equivalent of `chat()`. Instead of waiting for
    /// the full response, it streams token chunks through the provided
    /// `on_token` callback. When the stream completes:
    /// - If no tool calls: returns the accumulated response
    /// - If tool calls: enters the non-streaming tool loop (since tool
    ///   execution must complete before the next request)
    ///
    /// The `on_token` callback is called with each content token chunk.
    /// The `on_thinking` callback is called with each thinking chunk.
    /// Both callbacks must be `Send + Sync` for use in async tasks.
    ///
    /// If `cancel_token` is provided and becomes cancelled during streaming,
    /// the stream is aborted and the accumulated partial content is returned
    /// as the response.
    pub async fn chat_stream(
        &mut self,
        messages: Vec<ChatMessage>,
        on_token: impl Fn(String) + Send + Sync,
        on_thinking: impl Fn(String) + Send + Sync,
        on_tool_call: impl Fn() + Send + Sync,
        cancel_token: Option<tokio_util::sync::CancellationToken>,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        for m in &messages {
            log::debug!("Hit {} with (stream):", self.model);
            log::debug!(
                "\t{:?}: '{}'",
                m.role,
                crate::logging::truncate_for_log(&m.content, 80)
            );
        }

        let request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Apply optional settings
        let request = self.apply_optional_settings(request);

        // Push initial messages to history
        for m in request.messages.clone() {
            self.history.push(m);
        }

        // Store how many messages we started with
        self.initial_message_count = self.history.messages().len();

        // Start the streaming request
        let mut stream = self
            .ollama
            .send_chat_messages_stream(self.build_request())
            .await?;

        // Accumulate the full response while streaming
        let mut full_content = String::new();
        let mut full_thinking: Option<String> = None;
        let mut final_data = None;
        let mut tool_calls: Vec<ollama_rs::generation::tools::ToolCall> = Vec::new();
        let mut model = String::new();
        let mut created_at = String::new();

        use futures::StreamExt;

        while let Some(chunk_result) = stream.next().await {
            // Check for cancellation during streaming
            if let Some(ref ct) = cancel_token
                && ct.is_cancelled()
            {
                log::debug!("Stream cancelled by user");
                break;
            }

            match chunk_result {
                Ok(chunk) => {
                    // Stream content tokens
                    if !chunk.message.content.is_empty() {
                        on_token(chunk.message.content.clone());
                        full_content.push_str(&chunk.message.content);
                    }

                    // Stream thinking tokens
                    if let Some(ref thinking) = chunk.message.thinking {
                        on_thinking(thinking.clone());
                        if let Some(ref mut accumulated) = full_thinking {
                            accumulated.push_str(thinking);
                        } else {
                            full_thinking = Some(thinking.clone());
                        }
                    }

                    // Collect tool calls from the response
                    if !chunk.message.tool_calls.is_empty() {
                        tool_calls = chunk.message.tool_calls.clone();
                    }

                    // Capture metadata from any chunk
                    if !chunk.model.is_empty() {
                        model = chunk.model.clone();
                    }
                    if !chunk.created_at.is_empty() {
                        created_at = chunk.created_at.clone();
                    }

                    // On final chunk, capture final_data
                    if chunk.done {
                        final_data = chunk.final_data.clone();
                    }
                }
                Err(()) => {
                    // Stream error — break and let the coordinator handle it
                    break;
                }
            }
        }

        // Build a ChatMessageResponse from the accumulated content
        if !tool_calls.is_empty() {
            // Notify the event loop that tool calls were detected
            // (so it can transition LlmState to ToolCall)
            on_tool_call();

            // Build response with tool calls for process_response
            let msg_with_tools = ollama_rs::generation::chat::ChatMessage {
                role: ollama_rs::generation::chat::MessageRole::Assistant,
                content: full_content,
                tool_calls: tool_calls.clone(),
                images: None,
                thinking: full_thinking,
            };

            let response = ChatMessageResponse {
                model,
                created_at,
                message: msg_with_tools,
                logprobs: None,
                done: true,
                final_data,
            };

            // Content was already streamed via on_token callback —
            // mark as already_streamed to prevent InterToolText duplication.
            self.process_response(response, /*already_streamed=*/ true)
                .await
        } else {
            // No tool calls — this is the final response
            // Push to history
            self.history.push(ollama_rs::generation::chat::ChatMessage {
                role: ollama_rs::generation::chat::MessageRole::Assistant,
                content: full_content.clone(),
                tool_calls: Vec::new(),
                images: None,
                thinking: full_thinking.clone(),
            });

            let msg = ollama_rs::generation::chat::ChatMessage {
                role: ollama_rs::generation::chat::MessageRole::Assistant,
                content: full_content,
                tool_calls: Vec::new(),
                images: None,
                thinking: full_thinking,
            };

            Ok(ChatMessageResponse {
                model,
                created_at,
                message: msg,
                logprobs: None,
                done: true,
                final_data,
            })
        }
    }

    /// Apply optional settings to request
    fn apply_optional_settings(&self, mut request: ChatMessageRequest) -> ChatMessageRequest {
        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        request
    }

    /// Build a request from current history with ephemeral messages prepended
    fn build_request(&self) -> ChatMessageRequest {
        // Build messages: ephemeral first, then history
        let mut messages =
            Vec::with_capacity(self.ephemeral_messages.len() + self.history.messages().len());
        messages.extend(self.ephemeral_messages.iter().cloned());
        messages.extend(self.history.messages().iter().cloned());

        let mut request =
            ChatMessageRequest::new(self.model.clone(), messages).options(self.options.clone());

        // Add tools - need to convert our CustomToolInfo to ollama-rs's ToolInfo
        // We serialize ours and it's compatible
        let tools_json = serde_json::to_string(&self.tool_infos).unwrap_or_default();
        let tools: Vec<ollama_rs::generation::tools::ToolInfo> =
            serde_json::from_str(&tools_json).unwrap_or_default();
        request = request.tools(tools);

        if let Some(ref think) = self.think {
            request = request.think(think.clone());
        }

        request
    }

    /// Process response, handling tool calls with event emission.
    ///
    /// `already_streamed` should be `true` when the content was already
    /// streamed via `chat_stream()` — this prevents emitting an extra
    /// `PreToolContent` event that would duplicate the text.
    async fn process_response(
        &mut self,
        resp: ChatMessageResponse,
        already_streamed: bool,
    ) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check if there are tool calls
        if !resp.message.tool_calls.is_empty() {
            // Accumulate pre-tool content if present
            let has_content = !resp.message.content.trim().is_empty();
            let has_thinking = resp.message.thinking.is_some();

            if has_content || has_thinking {
                // Only accumulate content into pre_tool_content when it was
                // already streamed (first round via chat_stream). In that case,
                // take_pre_tool_content() is used by send_message_stream()
                // to compute post_tool_content (final response minus pre-tool
                // prefix) and to emit StreamBlockDone.
                //
                // When already_streamed=false (subsequent rounds via
                // process_next), the content is displayed in real-time via
                // LlmEvent::InterToolText — accumulating it here would cause
                // the content to be included in pre_tool_display, which
                // send_message_stream() would then subtract from the final
                // response (or worse, StreamBlockDone would re-display it).
                if already_streamed {
                    if !resp.message.content.trim().is_empty() {
                        if !self.pre_tool_content.is_empty() {
                            self.pre_tool_content.push_str("\n\n");
                        }
                        self.pre_tool_content.push_str(&resp.message.content);
                    }
                    // Accumulate thinking (use the first one)
                    if self.pre_tool_thinking.is_none() {
                        self.pre_tool_thinking = resp.message.thinking.clone();
                    }
                }

                // Emit event — mark already_streamed so the TUI event loop
                // knows whether to skip InterToolText injection.
                self.emit_event(ChatEvent::PreToolContent {
                    content: resp.message.content.clone(),
                    thinking: resp.message.thinking.clone(),
                    already_streamed,
                });
            }

            // Push assistant message to history (with tool calls)
            self.history.push(resp.message.clone());

            // Execute each tool call
            let mut tools_executed = Vec::new();

            for call in resp.message.tool_calls.clone() {
                // Check for user cancellation before each tool call.
                // When Ctrl+C is pressed during multi-tool execution,
                // the cancel token is set and we stop the loop after
                // the current tool finishes — not between tokens.
                if let Some(ref ct) = self.cancel_token
                    && ct.is_cancelled()
                {
                    log::debug!(
                        "Tool loop cancelled by user after {} tools",
                        tools_executed.len()
                    );
                    return Err(ollama_rs::error::OllamaError::Other(
                        CANCELLED_BY_USER.to_string(),
                    ));
                }

                let tool_name = call.function.name.clone();
                let args = call.function.arguments.clone();

                log::debug!("Tool call: {:?}", call.function);

                let Some(tool) = self.tools.get_mut(&tool_name) else {
                    log::debug!(
                        "Unknown tool '{}'. Available: {}",
                        tool_name,
                        self.tools.keys().cloned().collect::<Vec<_>>().join(", ")
                    );
                    return Err(ollama_rs::error::OllamaError::ToolCallError(
                        ollama_rs::error::ToolCallError::UnknownToolName,
                    ));
                };

                let result = match tool.call(args.clone()).await {
                    Ok(result) => result,
                    Err(e) => {
                        log::warn!("Tool '{}' execution failed: {e}", tool_name);
                        log::debug!(
                            "  Arguments: {}",
                            serde_json::to_string(&args).unwrap_or_else(|_| args.to_string())
                        );
                        // W2 Wave Context (#116): Tool execution errors are now
                        // recoverable — push the error as a tool message so the
                        // LLM can self-correct within the same turn instead of
                        // aborting the conversation. Uses recovery::push_tool_result
                        // wrapper (migration point in #121).
                        let error_msg = format!(
                            "Error executing tool '{tool_name}': {e}. \
                             Please try again with different arguments or use a different approach."
                        );
                        self.history.push(ChatMessage::tool(error_msg));
                        tools_executed.push(tool_name.clone());
                        continue;
                    }
                };

                log::debug!("Tool response: {}", &result);

                // Inter-tool context check: detect overflow and truncate if needed
                let check_result = self.check_and_handle_context_overflow(result);

                // Check if compaction is needed - stop and emit event
                if check_result.needs_compaction {
                    // Push the current result to history before stopping
                    self.history.push(ChatMessage::tool(check_result.result));
                    tools_executed.push(tool_name);

                    // Emit compaction needed event
                    self.emit_event(ChatEvent::ContextNeedsCompaction {
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                        tools_executed: tools_executed.clone(),
                    });

                    // Return error to signal compaction needed
                    let tools_str = tools_executed.join(", ");
                    return Err(ollama_rs::error::OllamaError::Other(format!(
                        "CONTEXT_NEEDS_COMPACT:{}:{}:{}",
                        check_result.tokens_used,
                        self.context_window.unwrap_or(0),
                        tools_str
                    )));
                }

                // Emit context events
                if check_result.was_truncated {
                    let result_tokens = estimate_tokens(&check_result.result);
                    self.emit_event(ChatEvent::ContextTruncated {
                        tool_name: tool_name.clone(),
                        original_tokens: check_result.tokens_used,
                        new_tokens: result_tokens,
                        context_window: self.context_window.unwrap_or(0),
                    });
                } else if check_result.is_near_limit {
                    self.emit_event(ChatEvent::ContextNearLimit {
                        tool_name: tool_name.clone(),
                        tokens_used: check_result.tokens_used,
                        context_window: self.context_window.unwrap_or(0),
                    });
                }

                // Push (possibly truncated) result to history
                self.history.push(ChatMessage::tool(check_result.result));
                tools_executed.push(tool_name);
            }

            // Recurse to get next response
            Box::pin(self.process_next()).await
        } else {
            // No tool calls - this is the final response
            // Push to history
            self.history.push(resp.message.clone());

            Ok(resp)
        }
    }

    /// Process next response after tool calls
    async fn process_next(&mut self) -> ollama_rs::error::Result<ChatMessageResponse> {
        // Check for user cancellation before making next request
        if let Some(ref ct) = self.cancel_token
            && ct.is_cancelled()
        {
            log::debug!("process_next cancelled by user");
            return Err(ollama_rs::error::OllamaError::Other(
                CANCELLED_BY_USER.to_string(),
            ));
        }

        // Check context overflow before sending to Ollama
        if let (Some(ctx_window), Some(prompt)) = (self.context_window, &self.system_prompt) {
            let history_tokens = estimate_chat_messages_tokens(&self.history.messages());
            let system_tokens = estimate_tokens(prompt) + MESSAGE_OVERHEAD;
            let total_tokens = history_tokens + system_tokens;

            // Use emergency threshold to detect overflow
            let (_, _, _, emergency_threshold) = calculate_thresholds(ctx_window);
            let threshold = ctx_window.saturating_sub(emergency_threshold);

            if total_tokens > threshold {
                // Return error that will be caught by caller
                let msg = format!(
                    "Context overflow during tool execution: {} tokens used, {} available. Use /compact to reduce context.",
                    total_tokens, ctx_window
                );
                return Err(ollama_rs::error::OllamaError::Other(msg));
            }
        }

        let resp = self.ollama.send_chat_messages(self.build_request()).await?;

        // Non-streaming path — content was not streamed.
        self.process_response(resp, /*already_streamed=*/ false)
            .await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_continuation_tag_basic() {
        let content = r#"I've analyzed the first part. Let me continue.

<continuation_needed>
Reasoning paused: Analyzed file structure
Next step: Examine the main function
</continuation_needed>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Analyzed file structure");
        assert_eq!(tag.next_step, "Examine the main function");
        assert!(cleaned.contains("I've analyzed the first part"));
        assert!(!cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_multiline() {
        let content = r#"Some response here.

<continuation_needed>
Reasoning paused: Completed step 1
Next step: Process step 2
</continuation_need>"#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none(), "Should not parse without closing tag");
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_in_code_block() {
        let content = r#"Here's an example:

```
<continuation_needed>
Reasoning paused: In code block
Next step: Should not parse
</continuation_needed>
```

This should not be parsed as a continuation tag."#;

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(
            tag.is_none(),
            "Tags inside code blocks should not be parsed"
        );
        assert!(cleaned.contains("<continuation_needed>"));
    }

    #[test]
    fn test_parse_continuation_tag_empty_fields() {
        let content = r#"<continuation_needed>
Reasoning paused:
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Empty fields should return None
        assert!(tag.is_none());
    }

    #[test]
    fn test_parse_continuation_tag_partial_fields() {
        let content = r#"<continuation_needed>
Reasoning paused: Half way through analysis
Next step:
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // Should still parse if at least one field is filled
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Half way through analysis");
        assert!(tag.next_step.is_empty());
    }

    #[test]
    fn test_parse_continuation_tag_no_tag() {
        let content = "This is a normal response without any continuation tag.";

        let (cleaned, tag) = parse_continuation_tag(content);

        assert!(tag.is_none());
        assert_eq!(cleaned, content);
    }

    #[test]
    fn test_parse_continuation_tag_nested_tags() {
        // Nested tags shouldn't happen in practice, but if they do,
        // we parse from first open to first close and take the last matching values
        let content = r#"<continuation_needed>
Reasoning paused: First level
Next step: Second level
<continuation_needed>
Reasoning paused: Nested
Next step: Should ignore
</continuation_needed>
</continuation_needed>"#;

        let (_, tag) = parse_continuation_tag(content);

        // We find the first </continuation_needed> (after "ignore")
        // and parse the content between, which includes all lines
        // The last matching field values win
        assert!(tag.is_some());
        let tag = tag.unwrap();
        assert_eq!(tag.paused_at, "Nested"); // Last "Reasoning paused:" wins
        assert_eq!(tag.next_step, "Should ignore"); // Last "Next step:" wins
    }
}
