//! LLM events for the async TUI event loop
//!
//! When the LLM runs in a background task, it communicates with the
//! main event loop through `LlmEvent` messages sent via `mpsc` channel.
//!
//! # Architecture
//!
//! ```text
//! Event loop (main task)          LLM task (spawned)
//!     ←── LlmEvent::ViewAction ── ChannelView (ChatView proxy)
//!     ←── LlmEvent::StreamToken ── Streaming token chunk
//!     ←── LlmEvent::StreamThinking ── Streaming thinking chunk
//!     ←── LlmEvent::StreamDone ── Streaming complete (final_data)
//!     ←── LlmEvent::ToolCallStarted ── Tool calls detected in stream
//!     ←── LlmEvent::Complete  ── Result of handle_user_message()
//!     ←── LlmEvent::Error     ── LLM error
//!     ──→ CancellationToken    ── Ctrl+C cancellation
//! ```
//!
//! # Tool Message Ordering
//!
//! Tool messages from `debug_tools::TUI_CALLBACK` flow through a
//! separate `tool_call_rx` channel. They are drained in the event
//! loop (not in `render()`) and inserted before the streaming zone
//! when the LLM is in `ToolCall` or `Streaming` state, ensuring
//! correct visual ordering relative to streaming content.

use super::command_output::CommandOutput;
use super::session::ChatSession;
use super::view::TokenMetrics;

/// Events sent from the LLM background task to the main event loop.
pub enum LlmEvent {
    /// A view action was triggered during LLM processing.
    ///
    /// These are `ChatView` method calls made by the LLM handler
    /// (via `ChannelView`), forwarded to the event loop for rendering.
    ViewAction(ViewAction),

    /// A streaming token chunk arrived from the LLM.
    ///
    /// The event loop should append this text to the CURRENT
    /// `AssistantStreaming` message in the chat area.
    StreamToken(String),

    /// A streaming thinking chunk arrived from the LLM.
    ///
    /// The event loop should append this text to the CURRENT
    /// thinking block being streamed.
    StreamThinking(String),

    /// The current streaming CONTENT BLOCK is complete.
    ///
    /// This event is emitted when tool calls interrupt streaming.
    /// By the time this event arrives, the TUI event loop has
    /// already processed `ToolCallStarted` (which called
    /// `finalize_streaming_zone_as_is()`) — so the pre-tool
    /// content is already a stable `Assistant` message.
    ///
    /// This event exists solely to set `block_finalized = true`
    /// on the `App` and transition `LlmState` to `ToolCall`.
    /// It does NOT carry content for rendering.
    StreamBlockDone,

    /// Streaming is complete — replace the FINAL streaming message with
    /// the final markdown-rendered assistant response.
    ///
    /// This is the last event of a streaming turn. It finalizes the
    /// LAST content block (post-tool, or the only block if no tools).
    /// For turns with tool calls, this event is preceded by
    /// `StreamBlockDone` which finalized the pre-tool block.
    StreamDone {
        /// Full accumulated response content (for markdown rendering)
        content: String,
        /// Thinking content (if any, already accumulated)
        thinking: Option<String>,
        /// Token metrics from the final streaming chunk
        metrics: Option<TokenMetrics>,
    },

    /// The LLM call completed successfully (non-streaming path).
    ///
    /// Contains the updated session (with new messages, tokens, etc.)
    /// and final token counts for the status bar update.
    Complete {
        /// Updated session after the LLM call (boxed to reduce enum size)
        session: Box<ChatSession>,
        /// Total tokens used after the response
        used_tokens: usize,
        /// Maximum context window tokens
        max_tokens: usize,
        /// Context usage percentage (0-100)
        percent: u8,
    },

    /// Text content generated by the LLM between tool call rounds.
    ///
    /// When the LLM processes tool results and emits text before the
    /// next set of tool calls (via process_next()), the response arrives
    /// as a complete block rather than streaming tokens. This event
    /// carries the full inter-tool content that should be displayed
    /// immediately, before any subsequent tool calls are rendered.
    ///
    /// Unlike `StreamToken` (which is emitted in real-time during
    /// streaming), this event carries the FULL block content because
    /// process_next() uses send_chat_messages() (non-streaming).
    InterToolText {
        /// Markdown response content (may contain thinking tags)
        content: String,
        /// Token metrics from the response (if available)
        metrics: Option<TokenMetrics>,
    },

    /// The LLM call failed with an error.
    #[allow(dead_code)] // Error enum variant — used by LLM task error handling
    Error(String),

    /// The LLM call was cancelled by the user (Ctrl+C).
    Cancelled,

    /// Tool calls were detected in the streaming response.
    ///
    /// The event loop should transition the LLM state to `ToolCall`
    /// so the status bar shows "Running tool..." with a fresh spinner.
    ToolCallStarted,
}

impl std::fmt::Debug for LlmEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ViewAction(action) => f.debug_tuple("ViewAction").field(action).finish(),
            Self::StreamToken(token) => {
                // Truncate token display to avoid flooding debug logs
                let display = if token.len() > 20 {
                    format!("{}...", &token[..20])
                } else {
                    token.clone()
                };
                f.debug_tuple("StreamToken").field(&display).finish()
            }
            Self::StreamThinking(token) => {
                let display = if token.len() > 20 {
                    format!("{}...", &token[..20])
                } else {
                    token.clone()
                };
                f.debug_tuple("StreamThinking").field(&display).finish()
            }
            Self::StreamBlockDone => f.debug_struct("StreamBlockDone").finish_non_exhaustive(),
            Self::StreamDone {
                content: _,
                thinking: _,
                metrics,
            } => f
                .debug_struct("StreamDone")
                .field("metrics", metrics)
                .finish_non_exhaustive(),
            Self::Complete {
                session: _,
                used_tokens,
                max_tokens,
                percent,
            } => f
                .debug_struct("Complete")
                .field("used_tokens", used_tokens)
                .field("max_tokens", max_tokens)
                .field("percent", percent)
                .finish_non_exhaustive(),
            Self::InterToolText {
                content: _,
                metrics,
            } => f
                .debug_struct("InterToolText")
                .field("metrics", metrics)
                .finish_non_exhaustive(),
            Self::Error(msg) => f.debug_tuple("Error").field(msg).finish(),
            Self::Cancelled => write!(f, "Cancelled"),
            Self::ToolCallStarted => write!(f, "ToolCallStarted"),
        }
    }
}

/// View actions forwarded from the LLM background task.
///
/// Each variant corresponds to a `ChatView` method call.
/// The event loop applies these to the real `RatatuiView`.
#[derive(Debug)]
pub enum ViewAction {
    /// `ChatView::show_system(message)`
    ShowSystem(String),
    /// `ChatView::show_error(error)`
    ShowError(String),
    /// `ChatView::show_assistant_response(content, thinking)`
    ShowAssistantResponse {
        content: String,
        thinking: Option<String>,
    },
    /// `ChatView::show_token_metrics(metrics)`
    ShowTokenMetrics(TokenMetrics),
    /// `ChatView::show_context_warning(percent, message)`
    ShowContextWarning { percent: u8, message: String },
    /// `ChatView::show_compact_progress(message)`
    ShowCompactProgress(String),
    /// `ChatView::show_compact_complete(count, preserved_first, preserved_last)`
    ShowCompactComplete {
        count: usize,
        preserved_first: usize,
        preserved_last: usize,
    },
    /// `ChatView::show_markdown(content)`
    ShowMarkdown(String),
    /// `ChatView::show_thinking(thinking)`
    ShowThinking(String),
    /// `ChatView::clear_continuation_line()`
    ClearContinuationLine,
    /// `ChatView::show_command_output(output)`
    ShowCommandOutput(CommandOutput),
}
