//! Citation-integrity sensor.
//!
//! Guards the defect class the September 2026 bibliographic audit found: a
//! citation whose arXiv ID resolves to the right paper while the *attribution*
//! around it — institution, year, headline number — comes from somewhere else.
//! Seven sites were wrong in versioned files, and every one of them looked
//! authoritative: the ID was real, the title was real, and the sentence read as
//! if someone had checked. Nobody ever re-checks a citation that looks checked.
//!
//! **What this sensor can and cannot see.** It verifies *identity* — that the ID
//! cited is a real paper, that its real author list contains the surnames the
//! prose attributes to it, and that a withdrawn paper is never cited as support.
//! It cannot verify a *number*: "reduces latency by ~40%" against a paper that
//! reports "up to 20%" is invisible here, because reading a claim back to its
//! source is judgement, not string matching. An earlier draft of this design
//! claimed broad coverage; a reviewer pointed out it would have caught exactly
//! one of the seven defects. Saying so here is deliberate — a guard that
//! overstates its reach is the same disease it exists to prevent.
//!
//! Data lives in `tests/data/citation-manifest.json`, generated by
//! `scripts/generate-citation-manifest.py` from the arXiv API. Generation is a
//! maintainer step on purpose: this audit hit HTTP 429 on 19 of 58 requests from
//! one IP with 3s spacing, so a network call inside `cargo test` would be flaky,
//! and a test that needs re-running until green is worse than no test.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn rel(path: &Path) -> String {
    path.strip_prefix(repo_root())
        .unwrap_or(path)
        .display()
        .to_string()
}

/// One paper as the arXiv API actually reported it.
#[derive(Debug, serde::Deserialize)]
struct Paper {
    title: String,
    authors: Vec<String>,
    year: String,
    /// The withdrawal notice, verbatim, when the author retracted the paper.
    #[serde(default)]
    withdrawn: Option<String>,
}

fn manifest() -> BTreeMap<String, Paper> {
    let path = repo_root().join("tests/data/citation-manifest.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\n\
             Run: python3 scripts/generate-citation-manifest.py",
            rel(&path)
        )
    });
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", rel(&path)))
}

/// Every markdown/Rust file whose text may cite a paper.
///
/// The CHANGELOG is included on purpose: its `0.38.0` entry once cited a
/// withdrawn paper as evidence, and release notes are read as history.
fn scanned_files() -> Vec<PathBuf> {
    let root = repo_root();
    let mut out = Vec::new();

    for name in ["AGENTS.md", "README.md", "SMOKE_TEST.md"] {
        let p = root.join(name);
        if p.exists() {
            out.push(p);
        }
    }

    fn walk(dir: &Path, out: &mut Vec<PathBuf>, depth: usize) {
        if depth > 4 {
            return;
        }
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().unwrap_or_default().to_string_lossy();
                // Skipped, each for its own reason:
                // - `book` is mdBook output (gitignored). Its copies are stale by
                //   construction — the first run of this sensor reported all three
                //   of its findings against `doc/book/**`, which is generated.
                // - `adr` / `legacy` / `implementation-history` are historical by
                //   name and intent: they record what was once true and must not be
                //   edited to match the present.
                if name == "book"
                    || name == "target"
                    || name == "adr"
                    || name == "legacy"
                    || name == "implementation-history"
                {
                    continue;
                }
                walk(&path, out, depth + 1);
            } else if matches!(path.extension().and_then(|e| e.to_str()), Some("md" | "rs")) {
                out.push(path);
            }
        }
    }

    for dir in ["doc", "src", ".opencode"] {
        let p = root.join(dir);
        if p.is_dir() {
            walk(&p, &mut out, 0);
        }
    }
    out
}

/// Each citation's ID, paired with the attribution written next to it.
///
/// Scoping the window to the *same line* is load-bearing, and the first version of
/// this sensor got it wrong. It spanned from the previous ID anywhere in the file,
/// so a bare `**References:** arXiv:2212.10496` inherited the author name from a
/// heading three lines above, and `papers-reference.md` reported correct citations
/// as misattributions twenty times over. A false positive on a *correct* citation
/// is how a guard gets deleted instead of fixed.
///
/// Attribution appears on **both** sides of the ID in these documents, so both sides
/// are read:
///
/// ```text
/// Cuconasu et al. (2025, arXiv:2505.15561) note that this …
///      ^ before                                    ^ after (empty)
/// "Mamba: Linear-Time Sequence Modeling" (2312.00752) — Gu et al. 2023
///                                      ^ before        ^ AFTER — this is why the
///                                                        first version missed it
/// ```
///
/// A line that names no author — `**References:** arXiv:X`, `| Title | Authors | [arXiv:X] | 2025 |`
/// — yields empty windows on both sides and is skipped. Table rows have their own
/// schema and are checked harder by `bibliography_table_matches_the_manifest`.
fn citations_with_attribution(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();

    for line in text.lines() {
        let positions = id_positions(line);
        let mut cursor = 0usize;
        for (n, (start, id)) in positions.iter().enumerate() {
            if *start < cursor {
                continue;
            }
            let after_start = start + id.len();
            // The after-window ends at the next citation on the line, so a line
            // listing several papers cannot attribute one author to two IDs.
            let after_end = positions
                .get(n + 1)
                .map(|(next, _)| *next)
                .unwrap_or(line.len());
            let mut window = trim_to_entry_boundary(&line[cursor..*start]).to_string();
            if after_start <= after_end {
                let after = trim_after_boundary(&line[after_start..after_end]);
                if !after.trim().is_empty() {
                    window.push(' ');
                    window.push_str(after);
                }
            }
            out.push((id.clone(), window));
            cursor = after_start;
        }
    }
    out
}

/// Cut a window forward to the end of its own entry.
///
/// The mirror of `trim_to_entry_boundary`. A comma, cell or list separator starts the
/// next entry, so the following paper's author cannot leak in:
///
/// ```text
/// … Gu et al. 2026 (arXiv:2605.19932), Diógenes et al. 2026 …
///                                   ^ cut here — Diógenes belongs to the next entry
/// ```
fn trim_after_boundary(window: &str) -> &str {
    let cut = window
        .find([',', '|', ';'])
        .or_else(|| window.find(") ("))
        .unwrap_or(window.len());
    &window[..cut]
}

/// Cut a window back to the start of its own entry.
///
/// Entry separators in these documents are the table cell (`|`), the closed
/// parenthetical ending a previous citation (`),`), and the list separator (`;`).
/// Anything before the last one belongs to a different citation.
fn trim_to_entry_boundary(window: &str) -> &str {
    let mut w = window;
    for sep in ["|", ";"] {
        if let Some((_, tail)) = w.rsplit_once(sep) {
            w = tail;
        }
    }
    if let Some((_, tail)) = w.rsplit_once("),") {
        w = tail;
    }
    w
}

/// Byte offsets and text of every arXiv ID in the document.
fn id_positions(text: &str) -> Vec<(usize, String)> {
    let bytes: Vec<char> = text.chars().collect();
    let lower: Vec<char> = text.to_lowercase().chars().collect();
    let mut out = Vec::new();
    // Track char index -> byte offset so the returned window slices correctly.
    let mut byte_off: Vec<usize> = Vec::with_capacity(bytes.len() + 1);
    let mut off = 0usize;
    for c in &bytes {
        byte_off.push(off);
        off += c.len_utf8();
    }
    byte_off.push(off);

    let mut i = 0;
    while i + 5 < bytes.len() {
        if bytes[i].is_ascii_digit()
            && bytes[i + 1].is_ascii_digit()
            && bytes[i + 2].is_ascii_digit()
            && bytes[i + 3].is_ascii_digit()
            && bytes[i + 4] == '.'
        {
            let mut j = i + 5;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            let digits = &bytes[i + 5..j];
            if (4..=5).contains(&digits.len()) {
                // Two forms count as a citation:
                // - `arXiv:2510.04371` / `arxiv.org/abs/2406.11931` — labelled;
                // - `(2312.00752)` — a bare ID in a parenthetical, which the repo
                //   uses for Mamba and Megalodon. Requiring a label missed these,
                //   and `context_management_research.md` is where they live.
                let ctx_start = i.saturating_sub(24);
                let context: String = lower[ctx_start..i].iter().collect();
                let labelled = context.contains("arxiv") || context.contains("abs/");
                let parenthesised =
                    i > 0 && bytes[i - 1] == '(' && j < bytes.len() && bytes[j] == ')';
                if labelled || parenthesised {
                    out.push((byte_off[i], bytes[i..j].iter().collect::<String>()));
                }
            }
            i = j;
        } else {
            i += 1;
        }
    }
    out
}

/// Surnames the prose attributes to a citation.
///
/// The documents write attribution as `Name et al.` or `Name & Other`, so the
/// surname is the capitalised token before either marker. Only the surname is
/// checked, and only against a lowercased comparison, because the audit found
/// the real author list spells names differently from the prose ("Gui-Bo Zhu"
/// vs "Guibo Zhu") — a stricter comparison would flag correct citations.
fn claimed_surnames(line: &str) -> Vec<String> {
    let words: Vec<&str> = line.split_whitespace().collect();
    let mut out = Vec::new();
    for (i, word) in words.iter().enumerate() {
        let next = words.get(i + 1).copied().unwrap_or("");
        let is_attribution = next.starts_with("et") || next.starts_with('&');
        if !is_attribution {
            continue;
        }
        let cleaned = word.trim_matches(|c: char| !c.is_alphanumeric());
        let looks_like_name = cleaned.len() > 2
            && cleaned.chars().next().is_some_and(char::is_uppercase)
            && !cleaned.chars().all(char::is_uppercase);
        // Skip prose that reads like a title rather than an author.
        let is_stopword = matches!(
            cleaned,
            "Source" | "Paper" | "See" | "The" | "And" | "But" | "Institution"
        );
        if looks_like_name && !is_stopword {
            out.push(cleaned.to_lowercase());
        }
    }
    out
}

fn normalize(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_alphanumeric() || c.is_whitespace())
        .collect::<String>()
        .to_lowercase()
}

// ---------------------------------------------------------------------------
// Sensors
// ---------------------------------------------------------------------------

/// Every cited arXiv ID is in the canonical bibliography.
///
/// This is the completeness half, and it is the check the audit asked for: "new
/// citations must be added to `papers-reference.md` rather than inline". A paper
/// cited in a design document but absent from the bibliography means the citation
/// exists only at its use-site, where nothing reconciles it with the paper.
///
/// It reads the bibliography, not the manifest. An earlier version compared against
/// the manifest — which is generated *from* the citations, so it agreed with them
/// by construction and would have passed on an empty bibliography. A guard that
/// checks a file derived from the thing it guards verifies nothing.
///
/// The CHANGELOG is excluded because release notes legitimately cite papers that
/// must NOT be in the bibliography: a retracted one and a fabricated one, both as
/// corrections. Adding those to the canonical list would corrupt what it protects.
#[test]
fn cited_arxiv_ids_are_all_in_the_bibliography() {
    let bib_path = repo_root().join("doc/src/development/research/papers-reference.md");
    let bib = std::fs::read_to_string(&bib_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", rel(&bib_path)));
    let in_bib = |id: &str| bib.contains(id);

    let mut unknown: Vec<String> = Vec::new();
    for file in scanned_files() {
        if rel(&file).ends_with("CHANGELOG.md") || rel(&file).ends_with("papers-reference.md") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (id, _) in citations_with_attribution(&text) {
            if !in_bib(&id) {
                unknown.push(format!("{id} (in {})", rel(&file)));
            }
        }
    }

    assert!(
        unknown.is_empty(),
        "arXiv IDs cited in the repo but absent from the canonical bibliography:\n  {}\n\
         Add the paper to doc/src/development/research/papers-reference.md (table row,\n\
         prose entry, and BibTeX block) rather than citing it inline only.",
        unknown.join("\n  ")
    );
}

/// A withdrawn paper is never presented as support.
///
/// The audit's worst finding: `arXiv:2410.21337` was retracted by its author over
/// "critical issues identified in the methodology/results", and the repo cited its
/// headline number as the evidence that a design was viable. Citing a retracted
/// result is not a formatting error — it is the same class as a fabricated
/// citation, because the number was never trustworthy.
///
/// A mention that *reports* the withdrawal is not a citation of support, so lines
/// that say so are allowed through.
#[test]
fn withdrawn_papers_are_not_presented_as_support() {
    let papers = manifest();
    let withdrawn_ids: Vec<&String> = papers
        .iter()
        .filter(|(_, p)| p.withdrawn.is_some())
        .map(|(id, _)| id)
        .collect();

    if withdrawn_ids.is_empty() {
        return;
    }

    let mut offenders = Vec::new();
    for file in scanned_files() {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (n, line) in text.lines().enumerate() {
            let l = line.to_lowercase();
            let reports_retraction = l.contains("withdraw")
                || l.contains("retract")
                || l.contains("no longer")
                || l.contains("removed");
            if reports_retraction {
                continue;
            }
            for id in &withdrawn_ids {
                if line.contains(id.as_str()) {
                    offenders.push(format!("{}:{} — {id}", rel(&file), n + 1));
                }
            }
        }
    }

    assert!(
        offenders.is_empty(),
        "withdrawn papers cited (not merely reported as withdrawn):\n  {}\n\
         A retracted result cannot support a claim. Remove the citation, or state \
         the retraction inline.",
        offenders.join("\n  ")
    );
}

/// A surname attributed to a citation is on that paper's author list.
///
/// This is the misattribution half, and the reason the sensor exists: the audit
/// found prose crediting papers to DeepMind/Stanford, MIT CSAIL and "Stanford NLP"
/// that were actually from Columbia, PwC and the Chinese Academy of Sciences. None
/// of those IDs was wrong — only the attribution around them.
///
/// Attribution is read from the citation's own text window (see
/// `citations_with_attribution`), not from the whole line, so a line listing
/// several papers cannot cross-attribute.
#[test]
fn attributed_surnames_match_the_papers_author_list() {
    let papers = manifest();
    let mut offenders = Vec::new();

    for file in scanned_files() {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (id, window) in citations_with_attribution(&text) {
            let Some(paper) = papers.get(&id) else {
                continue;
            };
            let claimed = claimed_surnames(&window);
            if claimed.is_empty() {
                continue;
            }
            let real: Vec<String> = paper.authors.iter().map(|a| normalize(a)).collect();
            for surname in &claimed {
                let present = real
                    .iter()
                    .any(|full| full.split_whitespace().any(|part| part == surname))
                    || real.iter().any(|full| full.contains(surname.as_str()));
                if !present {
                    offenders.push(format!(
                        "{} — {id} has authors [{}], prose claims `{surname}`",
                        rel(&file),
                        paper
                            .authors
                            .iter()
                            .map(|a| a.split_whitespace().last().unwrap_or(a))
                            .collect::<Vec<_>>()
                            .join(", "),
                    ));
                }
            }
        }
    }

    assert!(
        offenders.is_empty(),
        "a citation attributes the paper to an author not on it:\n  {}\n\
         Verify against the paper itself — arXiv metadata, the venue proceedings, \
         or OpenAlex — before changing either side.",
        offenders.join("\n  ")
    );
}

/// The bibliography table's columns agree with the manifest.
///
/// `papers-reference.md` is the canonical reference list, and its table is the one
/// place where a paper's metadata is written *structurally* — title, authors, ID,
/// year, one per column. That makes it the only citation form a sensor can check
/// properly, so it is checked harder: the lead author's surname must be on the real
/// author list and the year column must match the real publication year.
///
/// Table rows are deliberately excluded from the prose sensor. A row is
/// `| Title | Authors | [arXiv:ID](url) | Year |`, so the text before the ID is the
/// title cell, and reading it as prose attribution produces the title's capitalised
/// words as claimed authors.
#[test]
fn bibliography_table_matches_the_manifest() {
    let papers = manifest();
    let path = repo_root().join("doc/src/development/research/papers-reference.md");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return;
    };

    let mut offenders = Vec::new();
    let mut checked = 0usize;

    for line in text.lines() {
        // A bibliography row cites through a markdown link to arxiv.org.
        if !line.trim_start().starts_with('|') || !line.contains("arxiv.org/abs/") {
            continue;
        }
        let cells: Vec<&str> = line.split('|').map(str::trim).collect();
        if cells.len() < 5 {
            continue;
        }
        let (authors_cell, id_cell, year_cell) = (cells[2], cells[3], cells[4]);
        let Some(id) = url_arxiv_id(id_cell) else {
            continue;
        };
        let Some(paper) = papers.get(&id) else {
            offenders.push(format!("row cites {id}, absent from the manifest"));
            continue;
        };
        checked += 1;

        // `Li et al. (38 authors)`, `Tosun & Buldur`, `Gao, Long` all lead with the
        // first author's surname once the parenthetical and list separators go.
        let lead = authors_cell
            .split(|c| c == '(' || c == '&' || c == ';' || c == ',')
            .next()
            .unwrap_or("")
            .split("et al")
            .next()
            .unwrap_or("")
            .trim()
            .trim_matches('*');
        if !lead.is_empty() {
            let real: Vec<String> = paper.authors.iter().map(|a| normalize(a)).collect();
            // Normalise the claim the same way as the author list. `DeepSeek-AI` is
            // the lead author of one entry, and the author list stores it as
            // `DeepSeek-AI` while `normalize` strips the hyphen — so comparing a raw
            // `deepseek-ai` against `deepseekai` reported a correct row as wrong.
            // Same trap as `Gui-Bo Zhu` vs `Guibo Zhu`: punctuation and diacritics
            // differ between how a paper writes a name and how a sensor splits it.
            let lead_norm = normalize(lead);
            let present = real
                .iter()
                .any(|full| full.split_whitespace().any(|part| part == lead_norm))
                || real.iter().any(|full| full.contains(lead_norm.as_str()));
            if !present {
                offenders.push(format!(
                    "{id}: table credits `{lead}`, arXiv lists [{}]",
                    paper
                        .authors
                        .iter()
                        .take(3)
                        .map(|a| a.split_whitespace().last().unwrap_or(a))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
        }

        if year_cell != paper.year {
            offenders.push(format!(
                "{id}: table says {year_cell}, arXiv says {} ({})",
                paper.year, paper.title
            ));
        }
    }

    assert!(
        checked > 10,
        "only {checked} bibliography rows parsed; the table shape may have changed"
    );
    assert!(
        offenders.is_empty(),
        "the bibliography table disagrees with the papers themselves:\n  {}\n\
         Verify against arXiv, the venue proceedings, or OpenAlex.",
        offenders.join("\n  ")
    );
}

/// The arXiv ID inside a markdown link cell, if the cell holds one.
fn url_arxiv_id(cell: &str) -> Option<String> {
    let (_, rest) = cell.split_once("arxiv.org/abs/")?;
    let id: String = rest
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.')
        .collect();
    let digits = id.split('.').nth(1)?;
    if (4..=5).contains(&digits.len()) {
        Some(id)
    } else {
        None
    }
}

/// The manifest records identity for every paper the repo cites.
///
/// Guards against a manifest entry being gutted to make a check pass: a paper
/// with no authors would silently satisfy the attribution sensor for any surname.
#[test]
fn manifest_entries_carry_real_metadata() {
    let papers = manifest();
    assert!(
        papers.len() > 20,
        "manifest holds only {} papers; it should cover every cited ID",
        papers.len()
    );

    for (id, paper) in &papers {
        assert!(!paper.title.trim().is_empty(), "{id} has no title");
        assert!(!paper.authors.is_empty(), "{id} has no authors");
        assert!(
            paper.year.len() == 4 && paper.year.chars().all(|c| c.is_ascii_digit()),
            "{id} has a malformed year: {:?}",
            paper.year
        );
    }
}
